Couchbase :: Fixed GRD-61145
IBM/universal-connectors pull request #127
Opened 2022-06-27 14:53 UTC by ldmahale108

Signed-off-by: Laxmikant Mahale <Laxmikant.Mahale@ibm.com>

2022-06-27 15:01 UTC, RefaelAdi requested changes

2022-06-27 15:01 UTC, RefaelAdi commented on filter-plugin/logstash-filter-couchbasedb-guardium/CouchbasedbOverFilebeatPackage/CouchbaseDB/filter.conf
> +      add_field => { "serverHostname" => "%{[host][hostname]}" }
it's should be add_field => { "serverHostname" => "%{[host][name]}" }

2022-06-27 15:01 UTC, RefaelAdi commented on filter-plugin/logstash-filter-couchbasedb-guardium/couchbasedbFilebeat.conf
> +			add_field => { "serverHostname" => "%{[host][hostname]}" }
also here.

2022-06-27 15:17 UTC, ldmahale108 commented on filter-plugin/logstash-filter-couchbasedb-guardium/CouchbasedbOverFilebeatPackage/CouchbaseDB/filter.conf
> +      add_field => { "serverHostname" => "%{[host][hostname]}" }
`add_field => { "serverHostname" => "%{[host][name]}" }`
also works and `%{[host][hostname]}` is a alternative way(solution).
**QA team has verified this fixes**

2022-06-27 17:29 UTC, ofer-haim requested changes
Please wait to hear from QA team about this hostname issue.

2022-06-28 13:44 UTC, ldmahale108 commented
since this is getting fixed as a part of INS-21528, closing this

2022-06-28 13:44 UTC, closed without merging