Add Add redshift spanner plugin
IBM/universal-connectors pull request #134
Opened 2022-07-10 18:18 UTC by sandeepkumarverma1

2022-07-14 05:00 UTC, sandeepkumarverma1 commented
Hi @Tal-Daniel  @PratikshaSonawane @AlexaNahum @ofer-haim 

This PR is for 2 conenctors AWS Redshift and GCP Spanner, since we already have multiple round of testing and review on this. I request kindly have a look and provide your approval if no major change is required .

Thanks
Sandeep Verma

2022-07-14 08:00 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +If you'd like to start with the most simple filter plugin, we recommend to follow all the steps in [How to write a Java filter plugin](https://www.elastic.co/guide/en/logstash/7.16/java-filter-plugin
we recommend following all

2022-07-14 08:03 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +      - In the 'Network and security settings', select security group inside VPC security group.
select the security group

2022-07-14 08:04 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +      - Now click on 'Add rule' and provide following details-
the following

2022-07-14 08:04 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +5. Now click on create cluster button.
the create

2022-07-14 08:05 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +1. Navigate to the Redshift Console and click on the cluster which is created and go to properties tab.
the cluster that you just created

2022-07-14 08:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +1. The log files will appear in the s3 bucket in hourly batches, and sometimes even later. Typical delay is 30-120 minutes.
A typical delay

2022-07-14 08:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +3. Error Logs : As mentioned in AWS standard document for Redshift Connector, UserActivity logs do not capture any error logs related with Syntax error or Authentication error. That's why we are capt
in the AWS standard

2022-07-14 08:16 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +4. Due to parser limitation, following are the details of changes and limitations-
the following

the changes

2022-07-14 08:16 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +    - Select queries with `PIVOT/UNPIVOT` will not be parsed by Connector.
the connector

2022-07-14 08:17 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +5. CREATE MATERIALIZED VIEW commands appear multiple times on S3 bucket, Guardium full SQL report and sniffer logs.
the S3

the Guardium full SQL report,

2022-07-14 08:17 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +6. Any query having key constraints (primary key, foreign key, unique key) may create duplicacy in logs because they are not enforced by Amazon Redshift, mentioned in AWS document. (https://docs.aws.
as mentioned

2022-07-14 08:19 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +For Redshift, grok/regex patterns are used to parse user activity and connection logs data.
connection log data

2022-07-14 08:19 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +* mutate filter - The mutate filter allows you to perform general mutations on fields. You can rename, replace, and modify fields in your events. More information around mutate filter can be found at
about the mutate

2022-07-14 08:19 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +For Redshift, "replace" is used as mutate filter configuration. It is used to Replace the value of an event field with a new value, or add the field if it doesn’t already exist. Replace mutate filter
used as a mutate filter configuration.

replace (lower case r)

The replace mutate filter

in the STAP

2022-07-14 08:20 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +   - ClusterName- User needs to provide the name of Redshift cluster.
The user

2022-07-14 08:21 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +* Database Name is made up of 3 values:
The database

2022-07-14 08:21 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +  - ClusterName- User needs to provide the name of Redshift cluster.
The user

2022-07-14 08:22 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +2. Enable the connector if it is already disabled, before proceeding uploading of the UC.
proceeding to upload the UC.

2022-07-15 08:08 UTC, Tal-Daniel requested changes
See comments below. 

Also, I recommend adding technical design notes to both READMEs, that describe how each plug-in works, in high level. 

Note to self: 
- Spanner plug-in weighs 27MB
- Spanner plug-in uses JavaScript 3rd-party BigQuery parser, and pending approval as well as copyright notice.

2022-07-20 10:06 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/src/main/java/com/ibm/guardium/redshift/Parser.java
> +
Sure tell, will update the team regarding the same

2022-07-20 10:21 UTC, sandeepkumarverma1 commented on 1
> +#
This message copied from other branch,. no duplicate here

2022-07-20 10:21 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> + 1. While connecting  third part tool (sqlworkbench/j), we need to add inbound rule to security group inside Redshift cluster
Done

2022-07-20 10:21 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/README.md
> +      - In the 'Network and security settings', select security group inside VPC security group.
Done

2022-07-20 10:24 UTC, sandeepkumarverma1 commented
Hi @Tal-Daniel,  @AlexaNahum 

I have checked-in the suggested changes, request you to please have a look and let me know if any change is required.,

Thanks
Sandeep Verma

2022-07-20 10:28 UTC, AlexaNahum approved these changes
very minor changes that I suggested inline

2022-07-20 10:28 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/S3OverRedshiftPackage/filter.conf
> +# user needs to provde the value for account_id (AWS account id) and cluster_name
the user

provide

2022-07-20 10:28 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +# user needs to provde the value for account_id (AWS account id) and cluster_name
the user

provide

2022-07-20 10:28 UTC, AlexaNahum commented on filter-plugin/logstash-filter-redshift-aws-guardium/userActivitylog-test.conf
> +# user needs to provde the value for account_id (AWS account id) and cluster_name
the user

provide

2022-07-25 11:35 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/S3OverRedshiftPackage/filter.conf
> +# user needs to provde the value for account_id (AWS account id) and cluster_name
done

2022-07-25 11:35 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +# user needs to provde the value for account_id (AWS account id) and cluster_name
Done

2022-07-25 11:35 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/userActivitylog-test.conf
> +# user needs to provde the value for account_id (AWS account id) and cluster_name
Done

2022-07-26 09:19 UTC, sandeepkumarverma1 commented
HI @Tal-Daniel  @PratikshaSonawane ,

Lets push Redshift Connector out of our bucket today.

2022-07-26 11:58 UTC, Tal-Daniel approved these changes
Approved, after move of Spanner plug-in to a different PR.

2022-07-27 05:32 UTC, PratikshaSonawane requested changes

2022-07-27 05:32 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +prefix =>"<prefix/>"
Add comments wherever possible explaining a bit on the parameter

2022-07-27 05:32 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +replace => { "serverHostnamePrefix" => "<account_id>-<cluster_name>" }
serverhostname has underscore (_) char in its prefix, please check it is hyphen or underscore

2022-07-27 05:32 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +# The user needs to provide the value for account_id (AWS account id) and cluster_name
The better approach will be taking accountId in input section from the user rather than asking to replace in filter, this is what is followed for other plugins.
This will facilitate GI as well

2022-07-27 05:32 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-redshift-aws-guardium/sample_Connection_Log .txt
> +authentication failure |Mon, 16 Mar 2022 08:18:14:766|::ffff:223.233.72.13 |1224 |1073742045|dev |meenakshi |password |0|TLSv1.2 |ECDHE-RSA-AES256-GCM-SHA384 |0| | | | |Windows 10 10.0 amd64 |Amazon
This file can be removed

2022-07-27 05:32 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-redshift-aws-guardium/sample_UserActivity_Log.txt
> +'2022-02-18T07:00:50Z UTC [ db=dev user=rdsdb pid=28991 userid=1 xid=575219 ]' LOG: SELECT 1
This file can be removed

2022-07-27 05:32 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-redshift-aws-guardium/src/main/java/com/ibm/guardium/redshift/RedShiftGuardiumConnector.java
> +					e.tag(RedShiftTags.LOGSTASH_TAG_JSON_PARSE_ERROR);
Please add logger message as well

2022-07-27 05:52 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +replace => { "serverHostnamePrefix" => "<account_id>-<cluster_name>" }
Its hyphen  as per Dev Notes, so no change is required.

----------------------------------------------Dev Notes-----------------------------------
server hostname: on cloud environments, hard-coding the server hostname can become a problem for
customers that want to see that traffic is flowing from each and every UC connector they configured on
Guardium. A better approach is to add a prefix for the server hostname with instance, account, or
subscription on the cloud that your filter gets the events from. For example, on AWS, this could be
"<AccountID>-www.aws.com", or "<dbtype>.amazonaws.com". Since we want to allow customers the
flexibility to create the differentiation between datasources, filter plug-ins on cloud services should support
stating server hostname as another field within the Logstash filter configuration stage, like mutate mutate {
add_field => "server_hostname_pattern" => "%{[accountID]}-%{[instanceID]}.aws.com" }mutate { add_field =>
"server_hostname_pattern" => "%{[connection_name]}.googlecloud.com" }mutate { add_field =>
"server_hostname_pattern" => "%{[subscriptionID]}-%{[instanceID]}.azure.com"

2022-07-27 05:53 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +# The user needs to provide the value for account_id (AWS account id) and cluster_name
Hi Pratiksha,

It was as is since beginning, changing anything here will require a testing so we will look at it at the time of GI packaging

2022-07-27 06:05 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/src/main/java/com/ibm/guardium/redshift/RedShiftGuardiumConnector.java
> +					e.tag(RedShiftTags.LOGSTASH_TAG_JSON_PARSE_ERROR);
Done

2022-07-27 06:06 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/sample_UserActivity_Log.txt
> +'2022-02-18T07:00:50Z UTC [ db=dev user=rdsdb pid=28991 userid=1 xid=575219 ]' LOG: SELECT 1
Done

2022-07-27 06:06 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/sample_Connection_Log .txt
> +authentication failure |Mon, 16 Mar 2022 08:18:14:766|::ffff:223.233.72.13 |1224 |1073742045|dev |meenakshi |password |0|TLSv1.2 |ECDHE-RSA-AES256-GCM-SHA384 |0| | | | |Windows 10 10.0 amd64 |Amazon
Done

2022-07-27 06:06 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +prefix =>"<prefix/>"
Done

2022-07-27 06:07 UTC, sandeepkumarverma1 commented
Hi @PratikshaSonawane ,

I have updated/checked-in the PR comments you have raised. Request you to please have a look.

@Tal-Daniel  Seems like we are good now to push today.

Thanks

2022-07-27 10:46 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-redshift-aws-guardium/redshift.conf
> +# The user needs to provide the value for account_id (AWS account id) and cluster_name
ok

2022-07-27 10:49 UTC, PratikshaSonawane approved these changes

2022-07-27 11:14 UTC, merged