Add CouchDB Plugin
IBM/universal-connectors pull request #142
Opened 2022-07-14 04:50 UTC by sandeepkumarverma1

2022-07-14 05:01 UTC, sandeepkumarverma1 commented
Hi @Tal-Daniel  @PratikshaSonawane @AlexaNahum @ofer-haim 

This PR is for CouchDB on Prem since we already have multiple round of testing and review on this. I request kindly have a look and provide your approval if no major change is required .

Thanks
Sandeep Verma

2022-07-14 09:13 UTC, AlexaNahum approved these changes
minor language fixes

2022-07-14 09:13 UTC, AlexaNahum commented on filter-plugin/logstash-filter-couchdb-guardium/README.md
> +1. Clone Logstash codebase & build its libraries as as specified in [How to write a Java filter plugin](https://github.com/logstash-plugins/logstash-filter-java_filter_example). Use branch 7.x (this
Clone the

2022-07-14 09:13 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +Below is a copy of the filter scope included [MariaDB.conf](MariaDB.conf) that shows a basic
scope, including a

2022-07-14 09:13 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +If you'd like to start with the most simple filter plugin, we recommend to follow all the steps in [How to write a Java filter plugin](https://www.elastic.co/guide/en/logstash/7.16/java-filter-plugin
recommend following

2022-07-19 05:51 UTC, PratikshaSonawane requested changes

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/README.md
> +## CouchDB Log Sample
Remove this from README

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/README.md
> +#### Input part:
Remove this as well

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/README.md
> +Before you can build & create an updated GEM of this filter plugin, set up your environment as follows: .
Remove this part

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/couchdb.conf
> +port => 8541
add placeholder here and not the exact values

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/src/main/java/com/ibm/guardium/couchdb/CouchdbGuardiumFilter.java
> +						event.tag(LOGSTASH_TAG_JSON_PARSE_ERROR);
log the exception as well

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/Sample_log.txt
> +[notice] 2022-03-07T10:52:59.169000Z couchdb@localhost <0.22894.18> a56cfc23f8 127.0.0.1:5984 127.0.0.1 sravanthi PUT /Students 400 ok 60
No need to add this file, please remove

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/src/main/java/com/ibm/guardium/couchdb/Parser.java
> +	private static final String EXCEPTION_TYPE_AUTHENTICATION_STRING = "LOGIN_FAILED";
These can also moved to ApplicationConstant file

2022-07-19 05:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-couchdb-guardium/src/main/java/com/ibm/guardium/couchdb/Parser.java
> +			record.setSessionId(event.getField(ApplicationConstant.ID) != null
sessionId cannot be set to NA. Please make use of hashcode like we did in Neptune connector.

2022-07-20 10:39 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-couchdb-guardium/README.md
> +Before you can build & create an updated GEM of this filter plugin, set up your environment as follows: .
This is standard as of now, we are reviewing the latest guidelines. Will make the changes accordingly in all conenctors

2022-07-20 10:41 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-couchdb-guardium/src/main/java/com/ibm/guardium/couchdb/Parser.java
> +	private static final String EXCEPTION_TYPE_AUTHENTICATION_STRING = "LOGIN_FAILED";
Avoiding this change as of now. This will be fixed in future release

2022-07-20 10:45 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-couchdb-guardium/src/main/java/com/ibm/guardium/couchdb/Parser.java
> +			record.setSessionId(event.getField(ApplicationConstant.ID) != null
For Couch DB as of now A unique ID from audit logs has been used, This was long due connector which was under UAT before new dev notes. We can take this change to new PR.

2022-07-20 11:13 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +Below is a copy of the filter scope included [MariaDB.conf](MariaDB.conf) that shows a basic
This section is removed from Readme

2022-07-22 07:17 UTC, PratikshaSonawane approved these changes

2022-07-24 09:00 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +If you'd like to start with the most simple filter plugin, we recommend to follow all the steps in [How to write a Java filter plugin](https://www.elastic.co/guide/en/logstash/7.16/java-filter-plugin
The link URL shows in the README preview. Sandeep, could you fix it so README preview shows only "How to write ..." with the appropriate link, and not showing the whole URL next to it?

2022-07-24 09:11 UTC, Tal-Daniel requested changes

2022-07-24 09:11 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchdb-guardium/gradle/wrapper/gradle-wrapper.properties.bak
> +zipStorePath=wrapper/dists
git rm

2022-07-24 09:11 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchdb-guardium/README.md
> +
I suggest to add another sentence here describing the high level design, meaning, that this plug-in prepares the Guardium Record object, and relies on Guardium internal CouchDB parser to parse the database command.

2022-07-25 05:48 UTC, sandeepkumarverma1 commented on docs/available_plugins.md
> +|  [Google Cloud PostgreSQL](../filter-plugin/logstash-filter-pubsub-postgresql-guardium/README.md)   | 13.0                  | Google Cloud                       | IBM                  | Pub/Sub (pu
Fixed by mistake, sorry about that

2022-07-25 05:51 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-couchdb-guardium/README.md
> +
Done

2022-07-25 05:51 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-couchdb-guardium/gradle/wrapper/gradle-wrapper.properties.bak
> +zipStorePath=wrapper/dists
Done

2022-07-25 05:52 UTC, sandeepkumarverma1 commented
Hi @Tal-Daniel ,

All suggested changes are dont, request you to please have a look and approve the PR

2022-07-25 11:56 UTC, Tal-Daniel approved these changes
Approved. SessionId issue will be dealt as a post release issue.

2022-07-25 12:02 UTC, merged