Add Spanner Plugin
IBM/universal-connectors pull request #145
Opened 2022-07-25 12:31 UTC by sandeepkumarverma1

Signed-off-by: Sandeep Kumar Verma1 <sandeep.kumar.verma1@ibm.com>

2022-07-26 07:58 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/sample-audit-logs.json
> +[
We can remove this file, to keep it consistent with other plugins structure

2022-08-08 09:16 UTC, Tal-Daniel requested changes
See comments below.

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +```
Please shorten by linking to conf and referring to copy what's within the filter section there, instead of copying the conf here. Refer to other plug-ins.

Also, the sentence feels like the first sentence in the README, rather than a sentence dedicated to this stage. Missing instruction to paste configuration in the Guardium data protection relevant place in the UI.

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +      message => "{'protoPayload':{'@type':'type.googleapis.com\/google.cloud.audit.AuditLog','authenticationInfo':{'principalEmail':'pankaj-g766@hcl.com'},'requestMetadata':{'callerIp':'168.149.184.
same goes here: refer and link to example conf for testing, for developers only, ... 

@AlexaNahum

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +1. Error Logs are not generated in GCP for spanner and this plugin does not support errors traffic in guardium.
Spanner

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +4. For Drop Database there is no DDL query required in spanner as there is only Delete button And on deleting database through spanner UI, we are not getting query parameter in audit logs. please ref
"...[, a]nd on deleting"
@AlexaNahum

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +Download the guardium_logstash-offline-plugin-gcp-pubsub-spanner.zip plug-in.
link?

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +8. Update the filter section to add the details from spanner_with_pubsub.conf file's filter part, omitting the keyword "filter{" at the beginning and its corresponding "}" at the end.
see comments above. You might as well delete above sections with conf related comments, and use these sentences as starting point, just link to the conf you refer to in items 7 and 8.

@AlexaNahum

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +This configuration file generates an Event and send it thru the installed filter plugin.
"... and send[s] it ..." @AlexaNahum

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/ExecuteSqlParser.java
> +	private static String replaceDDLRegex = "((?i)UNIQUE)|((?i)NULL_FILTERED)";
Regex patterns should have a comment next to them explaining what they do in plain English.

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/ExecuteSqlParser.java
> +	public static Map<String, List<String>> parseSQL(V8Object parser, String sql) throws Exception {
Could you add inline comments, or javadoc function comment, that explain reasoning behind multiple sections within function?

2022-08-08 09:16 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +	private static String redactedRegex = "\"[^\"]*\"|'[^']*'|\\b[\\d]+\\b";
Regex patterns should have a comment next to them explaining what they do in plain English.

2022-08-08 09:28 UTC, Tal-Daniel commented
Sandeep, could you also add the resources the JS file before build/compilation?

2022-08-08 13:10 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +This configuration file generates an Event and send it thru the installed filter plugin.
Good catch. I caught a few more things now, here is the new proposed sentence:

This configuration file generates an event and sends it through the installed filter plug-in.

2022-08-08 14:29 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/resources/LICENSE.txt
> + of this license document, but changing it is not allowed.
Remove file, not necessary as mentioned in NOTICE and in file. 
Also, reminder: please include the JS file before build, to this folder. Thanks.

2022-08-17 15:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> -1. Clone Logstash codebase & build its libraries as as specified in [How to write a java filter plugin](https://github.com/logstash-plugins/logstash-filter-java_filter_example). Use branch 7.x (this
I rather like this section. It could really help developers feel guided, when they are introduced to the plug-in and want to try to install it, run it, fix an issue. Can we agree to return this section, to be after limitations, in all plug-ins? 
@ofer-haim @PratikshaSonawane @AlexaNahum

2022-08-17 15:53 UTC, Tal-Daniel requested changes

2022-08-17 15:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/ExecuteSqlParser.java
> +	 * object values
Could you clarify? I did not understand.

2022-08-17 15:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/ExecuteSqlParser.java
>  	private static String customDDlRegex = "(\\w+\\s+(?i)table)\\s+([\\w]+)|(\\w+\\s+(?i)index)\\s+([\\w]+)|(\\w+\\s+(?i)view)\\s+([\\w]+)|(\\w+\\s+\\w+\\s+\\w+\\s+(?i)view)\\s+([\\w]+)|(\\w+\\s+(?i)dat
Could you help developers understand also what the regex is looking for, in general? for example, " ... to get object and verb values, by looking for words table, index, view, that appear _________ within the string."

2022-08-17 15:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/resources/LICENSE.txt
> + of this license document, but changing it is not allowed.
@sandeepkumarverma1 awaits removal & original JS file, if available.

2022-08-23 07:23 UTC, Tal-Daniel requested changes
See previous comments, and these changes regarding LICENSE and NOTICE:

2022-08-23 07:23 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/resources/LICENSE.txt
> + of this license document, but changing it is not allowed.
@sandeepkumarverma1 , instead of removing this file, please overwrite the plug-in LICENSE file with this one, as using GPL in a plug-in makes the whole plug-in under GPL license.

2022-08-23 07:23 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/NOTICE
> +The file bigquery.peg-es5-v6.js was modified by IBM Corporation from bigquery.pegjs which is a part of node-sql-parser (https://github.com/taozhi8833998/node-sql-parser) package which comes under the
Please add at the beginning of NOTICE that this plug-in is released under GPL, by IBM.

2023-01-10 04:36 UTC, sandeepkumarverma1 commented
This pull Request is very old, We have to build a new parser base. So dropping this PR as this is outdated now.

2023-01-10 04:36 UTC, closed without merging