Add Neptune Plugin
IBM/universal-connectors pull request #161
Opened 2022-08-24 06:49 UTC by Ashi-Jain1

Signed-off-by: Ashi Jain <Ashi.Jain1@ibm.com>

2022-08-24 06:52 UTC, Ashi-Jain1 commented
Hi @Tal-Daniel @PratikshaSonawane @AlexaNahum ,
We have raised Neptune PR, request to have a look.

Thanks

2022-08-24 09:52 UTC, AlexaNahum approved these changes

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +
plug-in

only supports

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +Ther are only one way to enable the audit logs by setting the value from 0 to 1 in parameter configuration. After that Audit logs will be enabled.
The only way to enable the audit logs is by setting the value from 0 to 1 in the parameter confuguration. 

After that, the audit logs..

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 3. Creating the database and Associating with the database Parameter Group.
associating

parameter

group

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +    * Select "DB Cluster Parameter Group" from the dropdown list of Type.
from the Type drop-down menu.

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 1. Click on newly created Parameter Group from Cluster Parameter Groups list.
the newly

the Cluster

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 3. Select "1" instead of "0" from value dropdown list of neptune_enable_audit_log, now it will  allow the neptune audit logs.
from the value drop-down menu for neptune_enable_audit_log. Neptune audit logs will now be allowed.

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 4. Finally click on the save changes button for save the changes.
Finally,

to save the changes

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +#### Creating the database and Associating with the database Parameter Group
associating

parameter

group

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 1. On Amazon Neptune console, choose Databases on left panel. And click on "Create database" on  landing page.
the Amazon

from the left panel. Click on..

in the landing page

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 2. Choose the default version of the neptune which will be auto populated.
of Neptune, which will be auto-populated.

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 4. Click on the checkbox of "Create notebook" under the  Notebook configuration and provide the  Notebook name.
checkbox for

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 6. Under the additional configuration following things needs to be provided.
configuration, the following

need

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +    * Select the created DB parameter group name from the dropdown list of "DB cluster parameter group" and select "Audit log" of Log exports.
drop-down menu for..

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 7. Finally click on the Create database button, this will take few minutes to finish the process and User can connect to this cluster when both the cluster and instance status show as Available.
Finally, 

button. It will take a few minutes to finish the process. You can...

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +### Viewing the logs entries on CloudWatch
log entries

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +_If user is facing connectivity issue while executing queries on notebook please ensure that appropriate permission for the port where neptune instance is running, has been granted on security group.
notebook,

(if still accurate-) please ensure that the necessary permissions have been granted on "security group,_ " for the port on which the Neptune instance is running.

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +* You must have Log Full Details policy enabled on the collector. The detailed steps can be found in step 4 on [this page](https://www.ibm.com/docs/en/guardium/11.4?topic=dpi-installing-testing-filte
have the

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 2. Enable the connector if it is already disabled, before proceeding uploading of the UC.
before uploading the UC.

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 4. Click the Plus sign to open the Connector Configuration dialog box.
Plus icon

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> + 8. _"type"_ field should match in input and filter configuration section. This field should be unique for every individual connector added.
The _"type"_

in the input

sections

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +1. Following important fields couldn't be mapped with Neptune audit logs
The following

2022-08-24 09:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +     - Neptune audit log doesn’t include error logs, so in Guardium we will not be able to show the same in SQL_ERROR & LOGIN_FAILED report. In case of Invalid queries, Records does not show on guard
The Neptune

show this in the..

(if still accurate-)In cases of invalid queries, an error message will appear in the Guardium logs instead of records.

2022-08-24 16:32 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-neptune-aws-guardium/NeptuneOverCloudWatchPackage/filter.conf
> +        grok{
Hi @ofer-haim , 
This is required to filter out system logs. We have also completed the performance test over it and same has been already shared with Tal, we are getting the expected counts. No issues have been observed by using this grok filter.

Thanks

2022-08-25 13:50 UTC, itai-g-weather-com approved these changes

2022-08-29 07:42 UTC, hadarkorny approved these changes

2022-09-08 14:00 UTC, Tal-Daniel requested changes
Looking good. Thanks. Added a few minor comments.

2022-09-12 11:18 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +Neptune plug-in supports the Apache TinkerPop Gremlin and W3C's SPARQL queries.
Suggested: "Neptune plug-in supports parsing of Apache TinkerPop Gremlin and W3C's SPARQL queries."
@AlexaNahum

2022-09-12 11:19 UTC, Tal-Daniel approved these changes
Thank you for the contribution and fixes, Ashi. This graph DB is a great addition to Universal connectors.

2022-09-12 11:22 UTC, merged

2022-09-12 11:29 UTC, AlexaNahum commented on filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> +Neptune plug-in supports the Apache TinkerPop Gremlin and W3C's SPARQL queries.
looks good @Tal-Daniel