Add Firestore Plugin
IBM/universal-connectors pull request #163
Opened 2022-08-24 09:55 UTC by BalramVerma1

Signed-off-by: Balram Verma <Balram.Verma@ibm.com>

2022-08-24 09:57 UTC, BalramVerma1 commented
Hi @Tal-Daniel @PratikshaSonawane @AlexaNahum 
We have raised Firestore PR, request to have a look.

2022-08-24 10:24 UTC, ofer-haim commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
can you please upgrade to gson:2.8.9? There is a CVE found in gson:2.8.6.

We will enter a whitesource script to this repository in order to detect CVEs and do the required actions

2022-08-24 10:24 UTC, ofer-haim commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/gradle.properties
> +LOGSTASH_CORE_PATH=C:/Guardium/logstash-7.14/logstash-core
I don't think there's a reason to commit this file. Was it added to previous plugins?

2022-08-24 10:24 UTC, ofer-haim commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/ApplicationConstants.java
> +	public static final String DEFAULT_IPV6 = "0000:0000:0000:0000:0000:FFFF:0000:0000";
Was this value tested?

2022-08-24 10:24 UTC, ofer-haim commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/Parser.java
> +/*
Doe this Parser very specific to Firestore? 
Seems like there are a couple of things we can extract from here to uc-commons to make this a bit more modular

2022-08-24 13:20 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +        7.1) From GCP console, after clicking on “Firestore” user can see Firestore console.
In the GCP console, click on "Firestore" to see the Firestore console.

2022-08-24 13:23 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +        7.3) User have to Enter the collection_id, document_id, field_name, field_type and field_value.
7.3) Enter the...

2022-08-24 13:26 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +#### Configure logging & filter the logs using resources, logs and severity levels to display
logs,

2022-08-24 13:27 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +#### Permissions and Roles Details
role details

2022-08-24 13:27 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +Following Identity and Access Management roles required to view and download logs:
The following

are required

2022-08-24 13:28 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +* If the user has owner access to the destination
destination:

2022-08-24 13:28 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +   1. add the sink's writer identity to topic and give it the Pub/Sub Publisher role and subscriber role.
the topic

2022-08-24 13:28 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +   2. add the sink's writer identity to subscription and give it the Pub/Sub subscriber role.
the subscription

2022-08-24 13:29 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +* In the Topic ID field, provide a unique topic name, for example, MyTopic.
name. For example,

2022-08-24 13:29 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +* Click on Create Topic button.
Create Topic. (no button)

2022-08-24 13:29 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +* Display the menu for the topic created in previous step and click on New subscription.
the previous

click New subscription.

2022-08-24 13:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +* Click Create button
Click Create. (no button)

2022-08-24 13:31 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +* Sink name: Provide an identifier for the sink; note that after the user create the sink, the user can't rename the sink, but can delete it and create a new sink.
after you create the sink, you cannot rename it. However, you can delete it and create a new sink.

2022-08-24 13:31 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +* Click on Create.
Click Create.

2022-08-24 13:32 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +  2. FireStore other Log - `EMERGENCY`, `ALERT`, `CRITICAL`, `NOTICE`, `DEBUG`, `DEFAULT`
Firestore? (lower-case s)

other logs?

2022-08-24 13:33 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +The Guardium universal connector is the Guardium entry point for native audit/data_access logs. The Guardium universal connector identifies and parses the received events, and converts them to a stan
Firestore?

2022-08-24 13:33 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +   * You must have Log Full Details policy enabled on the collector. The detailed steps can be found in step 4 on [this page](https://www.ibm.com/docs/en/guardium/11.4?topic=dpi-installing-testing-fi
the Log Full Details?

2022-08-24 13:34 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +2. First Enable the Universal Guardium connector, if it is Disabled already.
First, enable

connector if it is currently disabled.

2022-08-24 13:35 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +5. Update the input section to add the details from [firestore_pubsub_run.conf](PubSubFireStorePackage/firestore_pubsub_run.conf) file's input part, omitting the keyword "input{" at the beginning and
from the [

2022-08-24 13:35 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +6. Update the filter section to add the details from [firestore_pubsub_run.conf](PubSubFireStorePackage/firestore_pubsub_run.conf) file's filter part, omitting the keyword "filter {" at the beginning
from the [

2022-08-24 13:35 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +9. After the offline plug-in is installed and configuration is uploaded and saved in the Guardium machine, restart the Universal Connector using the Disable/Enable button.
the configuration

2022-08-24 13:36 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +2. Error Logs(SQL Error/LOGIN FAILED) are not generated in GCP for firestore and this plugin does not support errors traffic in Guardium.
Firestore?

plug-in

error traffic?

2022-08-24 13:38 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +3. Audit/Data access log doesn't contains server ip, Default value is set 0.0.0.0 as server IP.
The audit/data?

doesn't have a server IP? doesn't automatically contain a value for a server IP?

The default value for server IPs is set as?

2022-08-24 13:38 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +4. Some fields could not be mapped as no information regarding the same was available in the logs. Following important fields couldn't be mapped-
as no such fields were found in the logs?

The following

2022-08-25 09:52 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
Hi @ofer-haim ,
This plugin has been tested with both the team  changing the version may raise a stability concern.

2022-08-25 09:55 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/ApplicationConstants.java
> +	public static final String DEFAULT_IPV6 = "0000:0000:0000:0000:0000:FFFF:0000:0000";
Hi @ofer-haim ,
if you are asking about default_ipv6 value, yes this was tested.

2022-08-25 09:56 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/Parser.java
> +/*
Hi @ofer-haim ,
Sure, we can think about in future.

2022-08-25 13:54 UTC, itai-g-weather-com approved these changes

2022-08-30 15:56 UTC, ofer-haim commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
@BalramVerma1 I won't block this PR, but please build next plugins with 2.8.9. Also- this is a crucial fix

2022-08-30 15:58 UTC, ofer-haim commented
Please resolve conflict in available_plugins.md file

2022-09-01 06:50 UTC, PratikshaSonawane requested changes

2022-09-01 06:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +
Please add steps to view Audit logs

2022-09-01 06:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
> +1. Firestore is a NoSQL, document-oriented database. Unlike a SQL database, there are no tables or rows. Instead, the user stores data in documents, which are organized into collections.
Why is this added as limitation?

2022-09-01 06:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/Parser.java
> +	private static SessionLocator parserSesstionLocator(JsonObject inputJson) {
typo error in method name

2022-09-01 06:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/ApplicationConstants.java
> +	public static final String DATA_TYPE = "MYSQL";
We are parsing the query on our own, then why is this dataType set to MYSQL? Are we using that parser?

2022-09-01 06:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/Parser.java
> +			appUserName = CommonUtils.convertIntoString(authenticationJSON.get(ApplicationConstants.PRINCIPAL_EMAIL));
Is this appUserName or dbUsername? Both are mapped to the same value

2022-09-01 06:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/Parser.java
> +		record.setSessionId(getFieldValueByKey(inputJson, ApplicationConstants.INSERTID));
InsertId is unique for every request and not per session, so can we not implement the hash code value for sessionId as done earlier for other plugins?

2022-09-12 05:54 UTC, PratikshaSonawane approved these changes

2022-09-13 12:13 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-firestore-guardium/src/main/java/com/ibm/guardium/firestore/Parser.java
> +		record.setSessionId(getFieldValueByKey(inputJson, ApplicationConstants.INSERTID));
This will be handled in another PR. creating a sessionId that is based on a hash of several fields like DB name, server IP, clientIP, ports, ... is better.

2022-09-13 12:58 UTC, merged