Document DB Production Fix
IBM/universal-connectors pull request #184
Opened 2022-09-12 09:50 UTC by sandeepkumarverma1

Fix realease

2022-09-12 09:54 UTC, sandeepkumarverma1 commented
Hi @Tal-Daniel ,

This PR has the fix and latest plugin of document DB


Thanks
Sandeep Verma

2022-09-13 14:02 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +			sentenceObject = new SentenceObject(ns.split("\\.")[1]);
worth moving into function, as used more than once.

2022-09-13 14:02 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/test/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilterTest.java
> +import org.junit.jupiter.api.Test;
We need to scan the code again, as a result of this change.

2022-09-13 17:45 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilter.java
> -			log.debug("DocumentDB filter: Got Event: " + logEvent(e));
No Required, as their is a way thorough which QA team can get the guard Object in uc log file.

2022-09-14 10:33 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +			sentenceObject = new SentenceObject(ns.split("\\.")[1]);
Its minor change, and at this point touching logical statements can affect the stability. we are sharing the scan report soon.

2022-09-21 04:32 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
We have got the awesome approval, email shared by Tawanna

2022-09-21 04:33 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/test/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilterTest.java
> +import org.junit.jupiter.api.Test;
We have got the awesome approval, email shared by Tawanna

2022-09-21 04:33 UTC, sandeepkumarverma1 commented
Hi @Tal-Daniel 

I have responded back you all review comments, also we have got AWSOME approval. We are good to release the connector now.

2022-09-21 15:10 UTC, Tal-Daniel requested changes
Sandeep, thanks for the updates. Just as a last step, could you update the CHANGELOG.md with the key additions/changes/fixes in this PR? one line per fix would be enough. See MongoDB filter [CHANGELOG.md](https://github.com/IBM/universal-connectors/blob/main/filter-plugin/logstash-filter-mongodb-guardium/CHANGELOG.md), as example. If you could also summarize these within the PR description it would really help me and others understand what this PR is all about, and what changes go into v1.15 of this plug-in. I really appreciate it.

2022-09-22 10:48 UTC, sandeepkumarverma1 commented
HI Tal,

I have updated the Changelog.md file and PR description as suggested by you. Request you to please have a look

2022-09-22 15:06 UTC, Tal-Daniel approved these changes
Approved. 

Please resolve conflicts and sign-off. 
I suggest to avoid to do git push with force flag, unless necessary (for correcting sign-offs, for example).

2022-09-30 08:28 UTC, Tal-Daniel requested changes
Sandeep, just a few minor conflict resolution issues left:

2022-09-30 08:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/gradle/wrapper/gradle-wrapper.properties
>  distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Please change to 6.5.1 as appears in #194, [here](https://github.com/IBM/universal-connectors/pull/194/files#diff-adaa995c59cac442436eb9cf20a683cf7372b0177aff77a561832e3598701936R3).

2022-09-30 08:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
> +     implementation fileTree(dir: GUARDIUM_UNIVERSALCONNECTOR_COMMONS_PATH, include: "guardium-universalconnector-commons-*.*.*.jar")
Could you change logstash-core and common jar, to be as in #194, [here](https://github.com/IBM/universal-connectors/pull/194/files#diff-f6d9130ca8ada68fceede2c6fd4096bcce1281e7e8b256b4a5ceff3718990bb0R72-R73)? Use the _compile_ instruction instead of implementation, and the newer short "common-...jar".

jupiter version is fine.

2022-09-30 09:33 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
> +     implementation fileTree(dir: GUARDIUM_UNIVERSALCONNECTOR_COMMONS_PATH, include: "guardium-universalconnector-commons-*.*.*.jar")
Done

2022-09-30 09:34 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/gradle/wrapper/gradle-wrapper.properties
>  distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Hi Tal,
As disscussed in WSR any library change post UAT may impact the stability of source code. It can be taken as a ticket post release.

2022-10-02 12:39 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
> +     implementation fileTree(dir: GUARDIUM_UNIVERSALCONNECTOR_COMMONS_PATH, include: "guardium-universalconnector-commons-*.*.*.jar")
not done. Should be like lines 72-73, [here](https://github.com/IBM/universal-connectors/pull/194/files#diff-f6d9130ca8ada68fceede2c6fd4096bcce1281e7e8b256b4a5ceff3718990bb0R72-R73)

2022-10-02 12:45 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/gradle/wrapper/gradle-wrapper.properties
>  distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Please change the build script, Sandeep, to match Refael's standardization for Gradle 6.5.1, as already exists for all plug-ins in main branch. This has no effect on the run-time, but on the compilation and packaging of the plug-in.

2022-10-03 07:33 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/gradle/wrapper/gradle-wrapper.properties
>  distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Hi Tal,
We have created the ticket "https://jira.rtp.raleigh.ibm.com:8443/browse/UCX-202" to track this activity.

Thanks

2022-10-20 05:14 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
> +     implementation fileTree(dir: GUARDIUM_UNIVERSALCONNECTOR_COMMONS_PATH, include: "guardium-universalconnector-commons-*.*.*.jar")
Done

2022-10-20 05:14 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/gradle/wrapper/gradle-wrapper.properties
>  distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Done

2022-10-30 10:23 UTC, Tal-Daniel approved these changes

2022-10-30 10:26 UTC, RefaelAdi approved these changes

2022-10-30 10:40 UTC, merged