Add Couchbase DB Plugin
IBM/universal-connectors pull request #19
Opened 2021-11-02 16:07 UTC by vbhvmahajan

This is Couchbase DB plugin for Guardium Universal Connector.

Signed-off-by: Vaibhav Mahajan1 <vaibhav.mahajan1@ibm.com>

2021-11-03 12:49 UTC, ofer-haim approved these changes

2021-11-07 15:28 UTC, Tal-Daniel requested changes

2021-11-07 15:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchbasedb-guardium/build.gradle
> +pluginInfo.homepage        = "http://www.elastic.co/guide/en/logstash/current/index.html"
please remove your name, and private email. leave 'IBM' author, and '' in email array.
Consider changing homepage to point to this repository.

2021-11-07 15:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchbasedb-guardium/filter-test-beats.conf
> +   mutate { remove_field => ["serverHostname","@version","@timestamp","type","sequence","message","host","tags","input","log","ecs","agent","serverIP"]}
Please mutate inside IF conditional, as removing fields outside may remove necessary fields from events that should be parsed by other filter plugins. See other plug-ins.

2021-11-07 15:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchbasedb-guardium/filter-test-generator.conf
> +	mutate { remove_field => ["serverHostname","@version","@timestamp","type","sequence","message","host","tags","input","log","ecs","agent","serverIP"]}
same here

2021-11-07 15:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchbasedb-guardium/CouchbasedbOverFilebeatPackage/datasourceManifest.json
> +}
Please add "supported_platforms", in another PR (see sibling MongoDB plug-in, for example).

2021-11-07 15:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchbasedb-guardium/CouchbasedbOverFilebeatPackage/CouchbaseDB/manifest.json
> +	"developer": "Vaibhav Mahajan",
Plug-ins developed by IBM employees/sub-contractors should state "IBM" as the developer.

2021-11-07 15:28 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchbasedb-guardium/CouchbasedbOverFilebeatPackage/CouchbaseDB/filter.conf
> +   mutate { remove_field => ["serverHostname","@version","@timestamp","type","sequence","message","host","tags","input","log","ecs","agent","serverIP"]}
move mutate inside IF (see comment below).

2021-11-07 15:29 UTC, Tal-Daniel commented
Also, Vaibhav, please update available_plugins.md, if possible.

2021-11-08 09:09 UTC, Tal-Daniel approved these changes

2021-11-08 09:09 UTC, Tal-Daniel commented on docs/available_plugins.md
> +| [Couchbase](../filter-plugin/logstash-filter-couchbasedb-guardium/README.md)    | 6.6.2-9600        | On-premise / Iaas        | IBM    		| Filebeat (push) |
Thanks. Consider stating **Guardium Data Protection only**, if not tested on Guardium Insights yet, like other plug-ins stated, above.

2021-11-08 09:09 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-couchbasedb-guardium/README.md
> +			mutate { remove_field => ["serverHostname","@version","@timestamp","type","sequence","message","host","tags","input","log","ecs","agent","serverIP"]}
I generally suggest to refer to a conf file, specific section, if possible; follow DRY design pattern (don't repeat yourself), but you can leave it, I guess, if it's short.

2021-11-09 10:27 UTC, merged