Adding Neo4j plugin
IBM/universal-connectors pull request #20
Opened 2021-11-02 17:24 UTC by rasikashete3

This is Neo4j plugin for Guardium Universal Connector (GDP only)
Signed-off-by: Rasika Shete <rasika.shete@ibm.com>

2021-11-07 07:51 UTC, ofer-haim approved these changes

2021-11-09 08:18 UTC, Tal-Daniel requested changes
Added initial comments

2021-11-10 12:56 UTC, rasikashete3 commented on filter-plugin/logstash-filter-neo4j-guardium/src/main/java/com/ibm/guardium/neodb/Constants.java
> +	public static final String SERVER_HOSTNAME = "Neo4j.com";
For on-premise, we are getting server ip, so server hostname does not remain relevant.  Host name can be set to blank.

2021-11-10 16:04 UTC, ofer-haim commented on filter-plugin/logstash-filter-neo4j-guardium/README.md
> +	If your Guardium version is below 11.5, the port should not be 5000, 5141 or 5044, as Guardium Universal Connector reserves these ports for MongoDB events. To check the available ports on Windows, i
I agree

2021-11-14 08:38 UTC, ofer-haim approved these changes

2021-11-14 12:19 UTC, Tal-Daniel requested changes

2021-11-14 12:19 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-neo4j-guardium/README.md
> +	6. Update the filter section to add the details from the https://github.com/IBM/universal-connectors/tree/main/filter-plugin/logstash-filter-neo4j-guardium/NeodbOverFilebeatPackage/config.json  file
I think you linked to the wrong file. Did you mean to link to neo4jFilebeat.conf (Logstash configuration file) or config.json (Insights package file)? 

Please link to correct file, in markdown format instead of writing the whole URL. like [neo4jFilebeat.conf](https://github.com/IBM/)

2021-11-15 07:20 UTC, Tal-Daniel requested changes

2021-11-15 07:20 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-neo4j-guardium/NeodbOverFilebeatPackage/Neo4jDB/neo4jFilebeat.conf
> +	if [type] == "Neo4J_Log" {
Please use a tag as differentiator, while leaving type as "filebeat", as multiple data sorce types may use same port to send events thru Filebeat. Refer to other plug-ins.

2021-11-16 14:26 UTC, ofer-haim commented on filter-plugin/logstash-filter-neo4j-guardium/NeodbOverFilebeatPackage/Neo4jDB/neo4jFilebeat.conf
> +	if [type] == "Neo4J_Log" {
This is the configuration file that QA team tested for GDP, so we will use it for now.

2021-11-16 15:21 UTC, Tal-Daniel approved these changes
Texts can be improved later, and filter tag should be added if more than one plug-in are required to run simultaneously.

2021-11-16 15:31 UTC, merged