Mariadb_Onprem Bugfixes
IBM/universal-connectors pull request #212
Opened 2022-10-21 13:22 UTC by BalramVerma1

- Carriage Return (\r) and Next Line Char (\n) are removed from multiline queries
- Soruce Program will not show "MariaDB" value in it.
- SQL error report will show the correct DB Protocol value.

Signed-off-by: balram verma <balram.verma@ibm.com>

2022-10-30 11:02 UTC, Tal-Daniel requested changes
Reviewed, with some requests for comments clarifications regarding the 2 ways one can filter out events – Universal connector configuration file, and Filebeat configuration file.

2022-10-30 11:02 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.1.1-bin.zip
FYI: Please use Gradle 6.5.1, for future plug-ins.

2022-11-01 09:28 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDB.conf
> +}
Hi Tal,
Since these logs needs to be removed we made it as a part of configuration. Users can follow the readme instruction
to ignore any logs according to their need. For now we have added a statement which says "Ignore System logs".

If still it needs to go in filebeat we will do it with the story we are creating for gradle version change, as that will go in the UAT process again.

2022-11-01 09:28 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDB.conf
> +}
done

2022-11-01 09:28 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/filter.conf
> +}
done

2022-11-01 09:29 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-mariadb-guardium/src/main/java/com/ibm/guardium/mariadb/ParserHelper.java
> +			fullSql = builder.toString().replaceAll("\n|\r", " ").replaceAll("\\\\n|\\\\r", " ").replaceAll("\\\\'", "'").replaceAll("\\\\","").replaceAll("\\\\t", "");
Hi Tal,
This has been added because UCX-68 bug says we have to remove the \r \n from the query, we can make the change which you are suggesting once it is confirmed by Guardium parser team. So as of now we have to keep it as it is.

2022-11-01 09:35 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-mariadb-guardium/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.1.1-bin.zip
Yes, Tal we will take note for future connectors. This also need to be updated in  dev notes.
For now this change should go under UAT as per the process, we will create a separate  story for it.

2022-11-15 09:13 UTC, Tal-Daniel approved these changes

2022-11-15 09:17 UTC, AlexaNahum approved these changes

2022-11-15 10:13 UTC, PratikshaSonawane approved these changes

2022-11-15 11:44 UTC, merged