Added GI Packaging for Neptune-AWS
IBM/universal-connectors pull request #235
Opened 2022-12-15 07:12 UTC by AayushiPalod

Signed-off-by: Aayushi Palod <aayushi.palod@ibm.com>

2022-12-15 09:28 UTC, RefaelAdi requested changes

2022-12-15 09:28 UTC, RefaelAdi commented on verifiedUCPlugins.txt
> +filter-plugin/logstash-filter-neptune-aws-guardium/NeptuneOverCloudWatchPackage
This change is required for SaaS adjustments only, but a few more things are needed to adjust this plug-in for SaaS env. 
let's remove this change and adjust the plug-in separately.

2022-12-15 10:37 UTC, RefaelAdi approved these changes

2022-12-15 11:34 UTC, AlexaNahum reviewed
no content corrections

2022-12-15 16:02 UTC, apurva-birajdar approved these changes
Approved.

2022-12-18 13:40 UTC, Tal-Daniel approved these changes

2022-12-18 14:10 UTC, merged