Added GI Packaging for Greenplum
IBM/universal-connectors pull request #236
Opened 2022-12-15 07:31 UTC by Ashi-Jain1

Signed-off-by: Ashi Jain <Ashi.Jain1@ibm.com>

2022-12-15 09:32 UTC, RefaelAdi requested changes

2022-12-15 09:32 UTC, RefaelAdi commented on verifiedUCPlugins.txt
> +filter-plugin/logstash-filter-onPremGreenplumdb-guardium/GreenplumdbOverFilebeatPackage
This change is required for SaaS adjustments only, but a few more things are needed to adjust this plug-in for SaaS env.
Let's remove this change and adjust the plug-in separately.

2022-12-15 10:36 UTC, RefaelAdi approved these changes

2022-12-15 11:35 UTC, AlexaNahum reviewed
no content corrections

2022-12-18 13:53 UTC, Tal-Daniel requested changes

2022-12-18 13:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-onPremGreenplumdb-guardium/GreenplumdbOverFilebeatPackage/gi_templates.json
> +  "plugin_name": "GreenPlumDB Over Filebeat",
I suggest to fix this to Greenplum, as in https://greenplum.org, especially if this is text is shown to users in the UI.

2022-12-19 05:11 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-onPremGreenplumdb-guardium/GreenplumdbOverFilebeatPackage/gi_templates.json
> +  "plugin_name": "GreenPlumDB Over Filebeat",
Hello @Tal-Daniel , this text is not shown to users, User will see "GreenPlumDB" as a plugin name.
PFA screenshot .
Thanks

<img width="587" alt="image" src="https://user-images.githubusercontent.com/110586246/208351864-7424e11e-22a5-42ee-9166-2a1653cdef6a.png">

2022-12-20 11:27 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-onPremGreenplumdb-guardium/GreenplumdbOverFilebeatPackage/gi_templates.json
> +  "plugin_name": "GreenPlumDB Over Filebeat",
Thanks for checking. I would change all user facing mentions to "Greenplum".

2023-01-02 04:42 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-onPremGreenplumdb-guardium/GreenplumdbOverFilebeatPackage/gi_templates.json
> +  "plugin_name": "GreenPlumDB Over Filebeat",
The changes have been done; plug-in name changed to "Greenplum".
PFA screenshot.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/110586246/210195682-1f57a6ca-36b8-4c79-9196-ed0a474687b2.png">
Thanks

2023-01-03 10:21 UTC, Tal-Daniel approved these changes

2023-01-04 12:52 UTC, RefaelAdi approved these changes

2023-01-05 15:02 UTC, merged