Added GI packaging for MariaDB-AWS
IBM/universal-connectors pull request #237
Opened 2022-12-15 07:46 UTC by AayushiPalod

Signed-off-by: Aayushi Palod <aayushi.palod@ibm.com>

2022-12-15 09:31 UTC, RefaelAdi requested changes

2022-12-15 09:31 UTC, RefaelAdi commented on verifiedUCPlugins.txt
> +filter-plugin/logstash-filter-mariadb-aws-guardium/MariaDBOverCloudWatchPackage
This change is required for SaaS adjustments only, but a few more things are needed to adjust this plug-in for SaaS env.
Let's remove this change and adjust the plug-in separately.

2022-12-15 10:35 UTC, RefaelAdi approved these changes

2022-12-15 11:36 UTC, AlexaNahum reviewed
no content corrections

2022-12-15 16:13 UTC, apurva-birajdar approved these changes
No changes required.

2022-12-18 13:57 UTC, Tal-Daniel approved these changes

2022-12-18 14:10 UTC, merged