Add Spanner Plugin
IBM/universal-connectors pull request #242
Opened 2023-01-10 09:20 UTC by Ashi-Jain1

Signed-off-by: Ashi Jain <Ashi.Jain1@ibm.com>

2023-01-10 13:15 UTC, AlexaNahum approved these changes

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +   1. add the sink's writer identity to topic and give it the Pub/Sub Publisher and Subscriber role.
```suggestion
   1. add the sink's writer identity to the topic and give it the Pub/Sub Publisher and Subscriber role.
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +   2. add the sink's writer identity to subscription and give it the Pub/Sub Subscriber role.
```suggestion
   2. add the sink's writer identity to the subscription and give it the Pub/Sub Subscriber role.
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +##### Steps to Create service account credentials
```suggestion
##### Creating service account credentials
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +* Go to the Service accounts section of IAM & Admin console.
```suggestion
* Go to the Service accounts section of the IAM & Admin console. 
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +* Select project and click on Create Service Account.
```suggestion
* Select project and click Create Service Account.
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +* Click Continue. The user does not need to grant users access to this service account.
```suggestion
* Click Continue. You do not need to grant users access to this service account.
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +* Click the Create Key. The key is used by logstash input plug-in configuration file.
```suggestion
* Click the Create Key. The key is used by the Logstash input plug-in configuration file.
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +The purpose of this inclusion filter is to include required and exclude unnecessary logs on the basis of some parameter from data_access and activity logs.
```suggestion
The purpose of this inclusion filter is to include the required logs and exclude the unnecessary ones, on the basis of some parameter from data_access and activity logs.
```

2023-01-10 13:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +* You must have Log Full Details policy enabled on the collector. The detailed steps can be found in step 4 on [this page](https://www.ibm.com/docs/en/guardium/11.4?topic=dpi-installing-testing-filte
per GRD-66763, change to: The detailed steps can be found in step 4 under section Installing and testing the filter or input plug-in on a staging Guardium system on [this page](https://github.com/IBM/universal-connectors/blob/main/docs/developing_plugins_gdp.md)

2023-01-16 08:14 UTC, PratikshaSonawane requested changes

2023-01-16 08:14 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		accessor.setDbUser(getAppUserName(protoPayloadJsonObject));
Please check if the assigned value is dbuser name or app user name? Please verify if both can be set to the same value.

2023-01-16 08:14 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/test/java/com/ibm/guardium/spanner/SpannerFilterConnectorTest.java
> +	}
Here we have just added test cases where null checks are added over events, and no specific Fields are verified? Please add the correct test cases.

2023-01-17 07:25 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from Spanner audit/activi
Updated README.md as per the format.
Thanks

2023-01-17 07:26 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/ApplicationConstants.java
> +	public static final String DATA_PROTOCOL = "Spanner(GCP)";
Since, this is a freetext field and there is no parser for spanner in Guardium, we kept it as Spanner (GCP). We went through the dev notes and implemented in suggested manner. Even if any change is required, we will do it post-release.

2023-01-17 07:26 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +				+ getInstanceNameAndProjectId(resourceJsonObject, ApplicationConstants.COLON)
We looked at the code, as it is not impacting the sessionId. If required, we will do it post-release.

2023-01-17 07:27 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		accessor.setDbUser(getAppUserName(protoPayloadJsonObject));
In GCP platform we are using principalEmail to connect as well as same id is being used for Spanner DB Connection thats why we are keeping same email in both the fields.

2023-01-17 07:28 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		JsonObject authenticationJSON = protoPayloadJsonObject.get(ApplicationConstants.AUTHENTICATION_INFO)
We looked at the code; it is written in such a way that it will not throw a NullPointerException. In line 465, it is checking whether protoPayload has the Authentication_Info attribute or not.

2023-01-17 07:28 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/test/java/com/ibm/guardium/spanner/SpannerFilterConnectorTest.java
> +	}
We will do the changes post-release.

2023-01-18 11:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +## 5. Limitations
Please move this section just above "Configuring the Spanner filter in Guardium"

2023-01-18 11:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		accessor.setDbUser(getAppUserName(protoPayloadJsonObject));
For SpannerDB connection, I agree we use priincipalEmail. But where else do you want to say by GCP platform to connect?
What I understand is appUsername is the Username with which the user logged in to the App used to execute the queries. @Tal-Daniel Please correct me if I am wrong.
Same issue was raised for couch-db-on-prem, where it was fixed then, please check
Thank you

2023-01-18 11:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +				+ getInstanceNameAndProjectId(resourceJsonObject, ApplicationConstants.COLON)
@Tal-Daniel  Please suggest

2023-01-18 11:52 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		JsonObject authenticationJSON = protoPayloadJsonObject.get(ApplicationConstants.AUTHENTICATION_INFO)
Ok thanks

2023-01-18 11:52 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/test/java/com/ibm/guardium/spanner/SpannerFilterConnectorTest.java
> +	}
@Tal-Daniel  Please suggest

2023-01-18 11:54 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from Spanner audit/activi
Limitations section is placed at the bottom, please move it as suggested. Thanks

2023-01-18 12:31 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/ApplicationConstants.java
> +	public static final String DATA_PROTOCOL = "Spanner(GCP)";
Data protocol have some freedom for developers' decision, as far I know. 
@Ashi-Jain1, could you compare with other filter plug-ins that work on Google cloud? If you leave GCP in the end, then add a space "Spanner (GCP)". 

Also, if Spanner solely exist on Google cloud, it's needless tot mention that in parenthesis, TMHO. 

This constant change can be done in this PR, especially if no manipulation or conditional depend on it.

2023-01-18 12:37 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +				+ getInstanceNameAndProjectId(resourceJsonObject, ApplicationConstants.COLON)
I see where this is coming from: That's how you represent the DB name (service name).

2023-01-18 13:13 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		accessor.setDbUser(getAppUserName(protoPayloadJsonObject));
Hi Pratiskha,
Here as well we use key file which has principalEmail where the same email id is getting used.
But still if change is required, we will take it as post release.

Thanks

2023-01-19 05:47 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/README.md
> +This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from Spanner audit/activi
Hello @PratikshaSonawane ,

We have followed the guidelines provided in the template.
As per the template, limitations should be at the end.
PFA 
[guidelines.txt](https://github.com/IBM/universal-connectors/files/10453852/guidelines.txt)

[[UCX-146] [DocumentDB UC]:Readme file changes required - IBM Security](https://jira-ds.rtp.raleigh.ibm.com:8443/browse/UCX-146)

Thanks

2023-01-19 14:07 UTC, Tal-Daniel requested changes
Is the org/perboiled code originally developed by you? If not, we may need to add a NOTICE file, and keep original notice in files.

2023-01-24 14:35 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/test/java/com/ibm/guardium/spanner/SpannerFilterConnectorTest.java
> +	}
Ashi, please add tests following this PR, as Pratiksha implies, that validate the Record contents, not only not null. 
It's recommended to add tests as soon as possible in the process.

2023-01-29 10:44 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/ApplicationConstants.java
> +	public static final String DATA_PROTOCOL = "Spanner(GCP)";
Thanks Ashi. Resolved as changed to "Spanner. no need for retesting, as this is a language that Guardiam does not parse, but rather you supply the parser.

2023-01-29 10:58 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		accessor.setDbUser(getAppUserName(protoPayloadJsonObject));
Correct, @PratikshaSonawane. If no app username, please leave it empty, Ashi, as this is an optional field (according to [Record.java](https://github.com/IBM/universal-connectors/blob/main/common/src/main/java/com/ibm/guardium/universalconnector/commons/structures/Record.java#L53-L56))

2023-01-29 11:56 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +				+ getInstanceNameAndProjectId(resourceJsonObject, ApplicationConstants.COLON)
This is not interfering with the session hashing.

2023-01-29 15:34 UTC, Tal-Daniel commented
> Is the org/perboiled code originally developed by you? If not, we may need to add a NOTICE file, and keep original notice in files.

Ashi, a kind reminder.

2023-01-30 05:57 UTC, Ashi-Jain1 commented on filter-plugin/logstash-filter-pubsub-spanner-guardium/src/main/java/com/ibm/guardium/spanner/Parser.java
> +		accessor.setDbUser(getAppUserName(protoPayloadJsonObject));
Done the changes, changed the value of AppUserName to empty.

Thanks

2023-01-30 06:04 UTC, Ashi-Jain1 commented
> > Is the org/perboiled code originally developed by you? If not, we may need to add a NOTICE file, and keep original notice in files.
> 
> Ashi, a kind reminder.

Hi Tal,

Yes, this code is developed by HCL, confusion may have arisen due to the org package name. Will modify the package name post-release.
We have also sent the same over mail 1/23/2023. (Spanner PR Comments)

2023-01-30 09:37 UTC, PratikshaSonawane approved these changes

2023-02-05 13:47 UTC, Tal-Daniel approved these changes
Approved. Readme and unit tests comments will be resolved post-release.

2023-02-08 09:40 UTC, merged