Big query
IBM/universal-connectors pull request #245
Opened 2023-01-17 08:55 UTC by sandeepkumarverma1

Add BigQuery Plugin

2023-01-17 09:30 UTC, AlexaNahum approved these changes

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses a GCP (Google Cloud Platform) event logs into
```suggestion
This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses a GCP (Google Cloud Platform) event logs into a [Guardium record](https://github.com/IBM/universal-connectors/blob/main/common/src/main/java/com/ibm/guardium/universalconnector/commons/structures/Record.java) instance (which is a standard structure made out of several parts). The information is then sent over to Guardium. Guardium records include the accessor (the person who tried to access the data), the session, data, and exceptions. If there are no errors, the data contains details about the query "construct". The construct details the main action (verb) and collections (objects) involved. As of now, the BigQuery plug-in only supports Guardium Data Protection.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +This version is compliant with GDP v11.4 and above.Please refer to the [input plug-in repository](https://github.com/IBM/universal-connectors/tree/main/input-plugin/logstash-input-google-pubsub) for
```suggestion
This version is compliant with Guardium Data Protection v11.4 and above. Please refer to the [input plug-in repository](https://github.com/IBM/universal-connectors/tree/main/input-plugin/logstash-input-google-pubsub) for more information.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +### Steps to create Topic in Pub/Sub
```suggestion
### Create a topic in Pub/Sub
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +* Click on Create a topic
```suggestion
* Click ```Create a topic```
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +* Click on Create Topic button.
```suggestion
* Click ```Create Topic```.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +### Steps to create subscription in Pub/Sub
```suggestion
### Create a subscription in Pub/Sub
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +* Display the menu for the topic created in previous step and click on New subscription.
```suggestion
* Display the menu for the topic created in the previous step and click ```New subscription```.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +### Steps to create log sink in Pub/Sub
```suggestion
### Create a log sink in Pub/Sub
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +* Click on Create sink button.
```suggestion
* Click ```Create sink```.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +* User can filter the logs using log name, resource and  severity.
```suggestion
* You can filter the logs by log name, resource, and  severity.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +* Click Create Key. The key is used by logstash input plugin configuration file.
```suggestion
* Click ```Create Key```. The key is used by the Logstash input plug-in configuration file.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +* Select JSON and click Create.
```suggestion
* Select JSON and click ```Create```.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +3. Click Upload File and select the offline [guardium_logstash-offline-plugins-ps-bigQuery.zip](BigQueryOverPubSubPackage/guardium_logstash-offline-plugins-ps-bigQuery.zip) plug-in. After it is uploa
```suggestion
3. Click Upload File and select the offline [guardium_logstash-offline-plugins-ps-bigQuery.zip](BigQueryOverPubSubPackage/guardium_logstash-offline-plugins-ps-bigQuery.zip) plug-in. After it is uploaded, click ```OK```.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +4. Click Upload File and select the key.json file. After it is uploaded, click OK.
```suggestion
4. Click ```Upload File``` and select the key.json file. After it is uploaded, click ```OK```.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +7. Update the input section to add the details from [pubsub_big_query.conf](pubsub_big_query.conf) file's input part, omitting the keyword "input{" at the beginning and its corresponding "}" at the e
```suggestion
7. Update the input section to add the details from the [pubsub_big_query.conf](pubsub_big_query.conf) file's input part, omitting the keyword "input{" at the beginning and its corresponding "}" at the end.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +8. Update the filter section to add the details from [pubsub_big_query.conf](pubsub_big_query.conf) file's filter part, omitting the keyword "filter{" at the beginning and its corresponding "}" at th
```suggestion
8. Update the filter section to add the details from the [pubsub_big_query.conf](pubsub_big_query.conf) file's filter part, omitting the keyword "filter{" at the beginning and its corresponding "}" at the end.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +9. 'type' field should match in input and filter configuration section.This field should be unique for every individual connector added.
```suggestion
9. The 'type' fields should match in the input and filter configuration sections. This field should be unique for every individual connector added.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +10. Click Save. Guardium validates the new connector, and enables the universal connector if it was disabled. After it is validated, it appears in the Configure Universal Connector page.
```suggestion
10. Click ```Save```. Guardium validates the new connector, and enables the universal connector if it was disabled. After it is validated, it appears in the Configure Universal Connector page.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +1. Some fields could not be mapped as no information regarding the same was available in the logs
```suggestion
1. If no information regarding certain fields is available in the logs, those fields will not be mapped. 
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +9. Audit/Data access log doesn't contains server ip, Default value is set 0.0.0.0 as server IP.
```suggestion
9. The Audit/Data access log doesn't contain a server IP. The default value is set 0.0.0.0 for the server IP.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +1. Some fields could not be mapped as no information regarding the same was available in the logs
I actually suggest we delete this limitation altogether, as it is implied in step 10 below.

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +10. Some fields could not be mapped as no information regarding the same was available in the logs. Following important fields couldn't be mapped-
```suggestion
10. The following important fields cannot be mapped, as there is no information regarding these fields in the logs:
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +    - Source program : Not available with logs
```suggestion
    - Source program 
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +    - OS User : Not available with logs
```suggestion
    - OS User
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +    - Client HostName : Not available with logs
```suggestion
    - Client HostName 
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +12. When user tries to Create or Delete Dataset or Table using BigQuery UI options, then fileds like FULL SQL & Objects and Verbs column appear as blank, as for these actions we didn't receive any qu
```suggestion
12. When you try to create or delete a data set or table using BigQuery UI options, fields like the FULL SQL & Objects and Verbs column appear blank, because these actions don't receive any query from GCP logs. You can ignore these actions, by updating the inculsion filter:
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +13. Parser is not supporting queries in which a keyword is used as a table name or column name or in scenarios of nested parameters inside functions.
```suggestion
13. The parser does not support queries in which a keyword is used as a table name or column name, or in scenarios of nested parameters inside functions.
```

2023-01-17 09:30 UTC, AlexaNahum commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
> +14. The BigQuery audit log doesn’t include login failed logs, so in Guardium we will not be able to show this in the LOGIN_FAILED report.
```suggestion
14. The BigQuery audit log doesn’t include login failed logs, so these will not appear in the guardium LOGIN_FAILED report.
```

2023-01-29 16:14 UTC, Tal-Daniel requested changes
Please remove [resources/bigquery.peg.oldjson.old](filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/resources/bigquery.peg.oldjson.old), if not needed.

Please verify that *.peg.json files, as well as any other code was not copied from other sources during development. Otherwise, specify the source, where downloaded from, as we will need to ask for open-source clearance for them, and maybe add tribute not in NOTICE. 

See other comments inline.

2023-01-29 16:14 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/test/java/com/ibm/guardium/bigquery/ParserTest.java
> +		assertEquals("anandku@hcl.com", record.getAppUserName());
Please remove any sensitive personal info like email and IP addresses.

2023-01-29 16:14 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/PegBigQueryParser.java
> + */
Please add 2023 to all files.

2023-01-29 16:14 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/ExecuteSqlParser.java
> +	 */
could you add a few examples of regex matches, along this comment?

2023-01-29 16:14 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/CommonUtils.java
> +	}
Warning (?)  If this function is used, it may result in single line comments including code from next command lines. Could you explain why you use this?

2023-01-29 16:14 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/ApplicationConstants.java
> +	public static final String DATA_PROTOCOL_STRING = "BigQuery(GCP)";
Please change to "BigQuery". Does not require retesting.

2023-01-29 16:14 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/pubsub_big_query.conf
> +}
no need for output section, as far as I recall. Please compare with other filter plug-ins. @PratikshaSonawane to confirm.

2023-01-30 06:38 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/CommonUtils.java
> +	}
Hi Tal,

Since we are writing the parser here so we can safely use this. This was the issue with Guardium parser.

2023-01-30 06:43 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/pubsub_big_query.conf
> +}
Yes output section, needs to be removed

2023-01-30 06:44 UTC, PratikshaSonawane approved these changes

2023-01-30 09:17 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/test/java/com/ibm/guardium/bigquery/BigQueryGuardiumFilterTest.java
> +		assertNotNull(events);
ok

2023-01-30 09:18 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/test/java/com/ibm/guardium/bigquery/ParserTest.java
> +		assertEquals("anandku@hcl.com", record.getAppUserName());
Done

2023-01-30 09:18 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/PegBigQueryParser.java
> + */
Done

2023-01-30 09:18 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/ExecuteSqlParser.java
> +	 */
Done

2023-01-30 09:18 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/ApplicationConstants.java
> +	public static final String DATA_PROTOCOL_STRING = "BigQuery(GCP)";
Done

2023-01-30 09:18 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/pubsub_big_query.conf
> +}
Done

2023-01-30 09:20 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/CommonUtils.java
> +	}
> 

Hi Tal,
This response is similar to Spanner, this code is developed by HCL  so no need of notice or credit. We will modify the package name post release along with the test cases changes.

2023-01-30 09:21 UTC, sandeepkumarverma1 commented
> Please remove [resources/bigquery.peg.oldjson.old](filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/resources/bigquery.peg.oldjson.old), if not needed.
> 
> Please verify that *.peg.json files, as well as any other code was not copied from other sources during development. Otherwise, specify the source, where downloaded from, as we will need to ask for open-source clearance for them, and maybe add tribute not in NOTICE.
> 
> See other comments inline.

Hi Tal,
This response is similar to Spanner, this code is developed by HCL so no need of notice or credit. We will modify the package name post release along with the test cases changes.

2023-01-31 08:31 UTC, Tal-Daniel approved these changes
Approved. Thank you! 
Please resolve conflict. Meanwhile, I'll verify open-source approval.

2023-02-08 10:03 UTC, merged