Fixed UAT Bugs
IBM/universal-connectors pull request #260
Opened 2023-02-03 08:35 UTC by BalramVerma1

Signed-off-by: balram verma <balram.verma@ibm.com>

2023-02-05 12:18 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +4. Different third party tool may generate different system queries, so based on observation user need to modify queries in 'exclude line' of filebeat configuration.
```suggestion
4. Different third party tools may generate different system queries, so modify queries in the 'exclude line' of your Filebeat configuration as needed.
```

2023-02-05 12:19 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +3. Click Upload File and select the offline [logstash-filter-mariadb_guardium_filter.zip](MariaDBOverFilebeatPackage/logstash-filter-mariadb_guardium_filter.zip) plug-in. After it is uploaded, click
```suggestion
3. Click ```Upload File``` and select the offline [logstash-filter-mariadb_guardium_filter.zip](MariaDBOverFilebeatPackage/logstash-filter-mariadb_guardium_filter.zip) plug-in. After it is uploaded, click ```OK```.
```

2023-02-08 09:59 UTC, Tal-Daniel requested changes

2023-02-08 09:59 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/CHANGELOG.md
> +
@BalramVerma1, could you state the main changes in this version? before the downgrade, I'd add for example, the \n\r change, and also the shift from excluding in connector configuration to excluding at FileBeat level.

Explain in simple and compact English sentence please, for non-developers, if possible.

2023-02-08 09:59 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/src/main/java/com/ibm/guardium/mariadb/ParserHelper.java
> +			fullSql = builder.toString().replaceAll("\\\\n","\n").replaceAll("\\\\r","\r").replaceAll("\\\\'", "'").replaceAll("\\\\","").replaceAll("\\\\t","\t");
explain in CHANGELOG (see comment above),  and in commit message.

2023-02-09 06:32 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-mariadb-guardium/CHANGELOG.md
> +
done

2023-03-01 13:18 UTC, Tal-Daniel approved these changes

2023-03-01 13:42 UTC, RefaelAdi approved these changes

2023-03-01 14:24 UTC, ofer-haim approved these changes

2023-03-01 14:24 UTC, merged