Grd 66741
IBM/universal-connectors pull request #263
Opened 2023-02-08 16:55 UTC by RefaelAdi

Update MySQL on-prem plug-in's Readme file according to the new readme template that is defined.

2023-02-08 17:10 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +In order to install the Audit Plugin, please refer to the official MySQL [documentation](https://dev.mysql.com/doc/mysql-secure-deployment-guide/5.7/en/secure-deployment-audit.html):
```suggestion
In order to install the Audit Plug-in, please refer to the official MySQL [documentation](https://dev.mysql.com/doc/mysql-secure-deployment-guide/5.7/en/secure-deployment-audit.html):
```

2023-02-08 17:10 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +This guide provides detailed information on how to install the Audit Plugin, as well as best practices for configuring and using it in a secure manner.
```suggestion
This guide provides detailed information on how to install the Audit Plug-in, as well as best practices for configuring and using it in a secure manner.
```

2023-02-08 17:12 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +1. On the collector, go to Setup > Tools and Views > Configure Universal Connector.
```suggestion
1. On the collector, go to ```Setup``` > ```Tools and Views``` > ```Configure Universal Connector```.
```

2023-02-08 17:13 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +2. First enable the Universal Guardium connector, if it is disabled already.
```suggestion
2. First, enable the Guardium universal connector, if it is currently disabled.
```

2023-02-08 17:14 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +6. Follow the notes in the  "Input configuration" section.
```suggestion
6. Follow the notes in the ```Input configuration``` section.
```

2023-02-08 17:14 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +4. Type a name in the Connector name field.
```suggestion
4. Type a name in the ```Connector name``` field.
```

2023-02-08 17:14 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +3. Click the Plus sign to open the Connector Configuration dialog box.
```suggestion
3. Click the Plus sign to open the ```Connector Configuration``` dialog box.
```

2023-02-08 17:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +5. Select Connector template as "MySQL using Filebeat" or "MySQL using Syslog".
```suggestion
5. Select ```MySQL using Filebeat``` or ```MySQL using Syslog``` for the ```Connector template```.
```

2023-02-08 17:15 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +6. Follow the notes in the  "Input configuration" section.
```suggestion
6. Follow the notes in the  ```Input configuration``` section.
```

2023-02-08 17:16 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +8. Click Save. Guardium validates the new connector, and enables the universal connector if it was disabled. After it is validated, it appears in the Configure Universal Connector page.
```suggestion
8. Click ```Save```. Guardium validates the new connector, and enables the universal connector if it was disabled. After it is validated, it appears in the ```Configure Universal Connector``` page.
```

2023-02-08 17:16 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +In the input configuration section, refer to the Filebeat section.
```suggestion
In the ```Input configuration``` section, refer to the Filebeat section.
```

2023-02-08 17:17 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +* If events with "(NONE)" local/remote IP addresses are not filtered, the filter plug-in will convert the IP to "0.0.0.0", as a valid format for IP is needed. However, this is atypical, since as mess
```suggestion
* If events with "(NONE)" local/remote IP addresses are not filtered, the filter plug-in will convert the IP to "0.0.0.0", as a valid format for IP is needed. However, this is atypical, since messages without users are filtered out.
```

2023-02-08 17:17 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +* Events in the filter are not removed, but tagged if not parsed (see [Filter result](#filter-result), below).
but rather tagged?

2023-02-08 17:18 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +*  If the dbname is not coming from command line, it will not get populated. If the user wants to see the dbname, either they need to send a use statement or send it on command line.
database name?

If you want to see the database name, send it either as a use statement or via the command line?

2023-02-08 17:18 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +*  If the dbname is not coming from command line, it will not get populated. If the user wants to see the dbname, either they need to send a use statement or send it on command line.
```suggestion
*  If the dbname is not coming from the command line, it will not get populated. If you want to see the dbname, either  send a use statement or send it on command line.
```

2023-02-08 17:38 UTC, ofer-haim approved these changes

2023-02-09 04:46 UTC, PratikshaSonawane requested changes

2023-02-09 04:46 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
>  This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from the MySQL audit into
Please add the link for GuardRecord as well.. This one
 [Guardium record](https://github.com/IBM/universal-connectors/blob/main/common/src/main/java/com/ibm/guardium/universalconnector/commons/structures/Record.java)

2023-02-09 04:46 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
Steps to View Audit Logs are missing

2023-02-09 04:46 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +   	filebeat.inputs:
Please check the formatting according to other README, Cassandra can be referred

2023-02-09 04:46 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +   tags: ["<tag_name>>"]
Do we need to handle multiline audit logs? If yes please add the details

2023-02-09 04:46 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> -### Not supported
This "Not Supported" section, can be added as Limitations?

2023-02-09 04:46 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +• You must have permission for the S-Tap Management role. The admin user includes this role, by default.
Details about LFD policy missing. Do we not upload the java plugin for this? is it by default available?

2023-02-09 07:48 UTC, RefaelAdi commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +   tags: ["<tag_name>>"]
I compared it with an existing filebeat.yml from a MySQL server that uses for testing and I didn't see any mention of multiline audit logs there. so I assumed that no need to handle it.

2023-02-09 07:49 UTC, RefaelAdi commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +   	filebeat.inputs:
It took from Cassandra README, with adjustments for MySQL.

2023-02-09 07:54 UTC, RefaelAdi commented on filter-plugin/logstash-filter-mysql-guardium/README.md
Isn't included in the referred guide here?
https://dev.mysql.com/doc/mysql-secure-deployment-guide/5.7/en/secure-deployment-audit.html

2023-02-09 07:56 UTC, RefaelAdi commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +• You must have permission for the S-Tap Management role. The admin user includes this role, by default.
No need to upload the Mysql on-prem plugin, it by default available.

2023-02-09 08:55 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +   tags: ["<tag_name>>"]
Ok thanks

2023-02-09 08:55 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +• You must have permission for the S-Tap Management role. The admin user includes this role, by default.
About LFD policy details?

2023-02-09 08:57 UTC, RefaelAdi commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +• You must have permission for the S-Tap Management role. The admin user includes this role, by default.
LFD policy means to see all log details in the reports, this is not related to the plug-in's configuration, did you see something about it in another plug-in's readme file? I'll check it.

2023-02-09 10:35 UTC, RefaelAdi commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> -### Not supported
This section is related to the Logstash installation which is not relevant anymore

2023-02-09 11:21 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mysql-guardium/README.md
> +• You must have permission for the S-Tap Management role. The admin user includes this role, by default.
I have a comment for this that might be relevant:  @PratikshaSonawane  @RefaelAdi , we recently removed the recommendation to configure the LFD policy from the before you begin section for all the plug-in readmes. (Pratiksha maybe you remember this from GRD-64294 and UCX-228.)

Instead, we put a general recommendation to configure policies per the user's requirements with a link to the policy section on the main page.

2023-02-12 14:48 UTC, RefaelAdi commented on filter-plugin/logstash-filter-mysql-guardium/README.md
I added another guide - the 2 guides should cover all the auditing configuration instructions

2023-02-13 06:58 UTC, PratikshaSonawane approved these changes

2023-02-13 07:35 UTC, merged