feat: INS-26881 UC Snowflake takeover
IBM/universal-connectors pull request #268
Opened 2023-02-14 13:57 UTC by chirag-ibm

Signed-off-by: Chirag Soni <chirag.soni@ibm.com>

2023-02-14 14:07 UTC, chirag-ibm commented
Wicked CLI scan is already executed. The report is available here, https://ibm.box.com/s/u7gqo5wjuyy01f4gk1b2dn90lm343vb8

2023-02-15 11:40 UTC, ofer-haim approved these changes

2023-02-19 07:56 UTC, ofer-haim approved these changes

2023-02-25 17:19 UTC, ofer-haim commented on filter-plugin/logstash-filter-snowflake-guardium/LICENSE
> +Copyright (c) 2020 infoinsights
After consulting with legal department it should be changed to:
```
MIT License
Copyright (c) 2020 infoinsights
© Copyright IBM Corp. 2023 All rights reserved.
```

2023-02-27 15:00 UTC, chirag-ibm commented on filter-plugin/logstash-filter-snowflake-guardium/LICENSE
> +Copyright (c) 2020 infoinsights
@ofer-haim , done. please verify

2023-02-27 15:18 UTC, johnhaldeman approved these changes

2023-02-27 15:18 UTC, johnhaldeman commented on filter-plugin/logstash-filter-snowflake-guardium/README.md
> +Have another question? [Open an issue](https://github.com/infoinsights/guardium-snowflake-uc-filter/issues) in this repo and we'll answer and post it here.
This suggests people with problems/questions should open an issue with the Information Insights repo? Should they contact support instead?

2023-02-27 15:18 UTC, johnhaldeman commented on filter-plugin/logstash-filter-snowflake-guardium/README.md
> +Have another question? [Open an issue](https://github.com/infoinsights/guardium-snowflake-uc-filter/issues) in this repo and we'll answer and post it here.
```suggestion
Have another question? [Open a support case](https://www.ibm.com/mysupport/s/) with IBM support
```

2023-02-27 15:24 UTC, ofer-haim commented on filter-plugin/logstash-filter-snowflake-guardium/README.md
> +Have another question? [Open an issue](https://github.com/infoinsights/guardium-snowflake-uc-filter/issues) in this repo and we'll answer and post it here.
Thanks @johnhaldeman,
@chirag-ibm I think we should remove that line, as customers already have support and potential customers should contact sales

2023-02-27 17:07 UTC, RefaelAdi requested changes

2023-02-27 17:07 UTC, RefaelAdi commented on filter-plugin/logstash-filter-snowflake-guardium/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.8-bin.zip
In order to adjust this plug-in need to update the gradle version to 6.5.1 and to make sure all the plug-ins tests are passed

2023-02-28 09:28 UTC, chirag-ibm commented on filter-plugin/logstash-filter-snowflake-guardium/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.8-bin.zip
@RefaelAdi, Done.

2023-03-01 07:27 UTC, RefaelAdi approved these changes

2023-03-01 07:51 UTC, PratikshaSonawane requested changes

2023-03-01 07:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-snowflake-guardium/build.gradle
> +pluginInfo.authors         = ['Information Insights LLC']
change pluginInfo.authors         = ['Information Insights LLC'] to  ['Information Insights LLC', 'IBM']

2023-03-01 07:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-snowflake-guardium/build.gradle
> +pluginInfo.email           = ['john.haldeman@infoinsightsllc.com']
Remove this

2023-03-01 07:51 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-snowflake-guardium/build.gradle
> +pluginInfo.homepage        = "http://www.infoinsightsllc.com"
Change this to "https://github.com/IBM/universal-connectors"

2023-03-01 09:38 UTC, PratikshaSonawane approved these changes

2023-03-01 09:46 UTC, merged