Enhance Test Checks [UCX-248]
IBM/universal-connectors pull request #278
Opened 2023-02-27 13:14 UTC by ankitapawar2

Enhance Test Checks for Spanner [UCX-248].

2023-02-27 13:22 UTC, ofer-haim approved these changes

2023-03-01 14:20 UTC, Tal-Daniel requested changes
Thank you, the tests validate the expected values for different commands now. 
Ankita, could you just remove personal info, like emails and real IP addresses before we merge?

2023-03-02 09:26 UTC, ankitapawar2 commented
> Thank you, the tests validate the expected values for different commands now. Ankita, could you just remove personal info, like emails and real IP addresses before we merge?

Hi Tal, real personal info has been replaced by dummy values. Thanks!

2023-03-02 13:10 UTC, Tal-Daniel approved these changes

2023-03-02 13:12 UTC, merged