Add Azure MySQL connector
IBM/universal-connectors pull request #371
Opened 2023-09-12 11:50 UTC by SubratoP1

2023-09-20 06:16 UTC, PratikshaSonawane requested changes

2023-09-20 06:16 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-azure-guardium/src/main/java/com/ibm/guardium/azuremysql/Constants.java
> +package com.ibm.guardium.azuremysql;
Please add copyright information at the beginning of the file

2023-09-20 06:16 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-azure-guardium/azure_mysql.conf
> +input
Please add copyright information at the beginning

2023-09-20 06:16 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-azure-guardium/src/test/java/com/ibm/guardium/azuremysql/AzureMysqlGuardiumFilterTest.java
> +/*
Please add copyright information

2023-09-20 06:16 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-azure-guardium/src/test/java/com/ibm/guardium/azuremysql/ParserTest.java
> +package com.ibm.guardium.azuremysql;
Please add copyright information

2023-09-21 05:52 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/src/main/java/com/ibm/guardium/azuremysql/Constants.java
> +package com.ibm.guardium.azuremysql;
Added the copyright information.

2023-09-21 05:52 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/src/test/java/com/ibm/guardium/azuremysql/AzureMysqlGuardiumFilterTest.java
> +/*
Added the copyright information.

2023-09-21 05:52 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/src/test/java/com/ibm/guardium/azuremysql/ParserTest.java
> +package com.ibm.guardium.azuremysql;
Added the copyright information.

2023-09-21 06:17 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/azure_mysql.conf
> +input
Hi Pratiksha,

We have never been asked to add copyright information in configuration file and the way it has been added in other projects configurations in GitHub, we have verified it is breaking the configuration.

So, copyright configuration has been added in all files other than conf.

Thanks
Subrato

2023-09-25 05:39 UTC, apurva-birajdar approved these changes

2023-09-25 06:47 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mysql-azure-guardium/azure_mysql.conf
> +input
Hi Subrato,
But the customer is not expected to run the conf as is. This is to maintain the copyright information. Also, we have some plugins which have only ruby code placed in conf files, then, in such cases we would not be able to add the copyright anywhere at all. So I request, we should add the same.

2023-09-25 10:02 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/azure_mysql.conf
> +input
Hi Pratiksha,

We added the copyright information in the conf. file please check and verify. 

Thanks
Subrato

2023-09-26 07:49 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mysql-azure-guardium/AzureMySQLOverAzureEventHub/filter.conf
> +			}
Why are you dropping USE commands?

2023-09-26 07:51 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mysql-azure-guardium/README.md
> +3. Azure EventHub is not capturing `syntactical error` queries logs, `Login Failed` logs, and logs using `az commands` (Ex below) and `REST API`.
formatting comment: Try to restrict code snippets to code snippets only; emphasize words using bold and italics, if really necessary. FYI @AlexaNahum

2023-09-26 07:53 UTC, Tal-Daniel commented on docs/available_plugins.md
> +* [Azure MYSQL](../filter-plugin/logstash-filter-mysql-azure-guardium/README.md)
move upwards a bit, if order is alphabetic.

2023-09-26 07:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mysql-azure-guardium/AzureMySQLOverAzureEventHub/filter.conf
> +			}
copyright notice?

2023-09-26 07:58 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mysql-azure-guardium/README.md
> +data contains details about the query "construct". The construct details the main action (verb) and collections (objects) involved.
The construct sentence is generic; for this plug-in I expected to see a sentence that explains that MySQL SQL commands are not parsed by this plug-in but rather forwarded as-is to Guardium to do the SQL parsing. @PratikshaSonawane @AlexaNahum @ofer-haim

2023-09-26 08:02 UTC, Tal-Daniel commented
Please sign-off every commit, @SubratoP1.

2023-09-26 10:09 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/AzureMySQLOverAzureEventHub/filter.conf
> +			}
Hi Tal,

This has been already discussed that we will add this after the post release. So that's why we are ignoring it.
We have added Copyright info to this file as well. 

Thanks
Subrato.

2023-09-26 10:18 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/README.md
> +data contains details about the query "construct". The construct details the main action (verb) and collections (objects) involved.
Hi Tal,

As per your suggestion we did the changes please check and verify.

Thanks
Subrato.

2023-09-26 11:04 UTC, PratikshaSonawane approved these changes

2023-09-27 12:46 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mysql-azure-guardium/README.md
> +data contains SQL commands are not parsed by this plug-in but rather forwarded as it is to Guardium to do the SQL parsing.
Thanks. Minor suggestion though:

> that _data_ contains SQL commands **that** are not parsed by ... ?

2023-09-27 13:26 UTC, apurva-birajdar approved these changes

2023-09-27 13:29 UTC, SubratoP1 commented on filter-plugin/logstash-filter-mysql-azure-guardium/README.md
> +data contains SQL commands are not parsed by this plug-in but rather forwarded as it is to Guardium to do the SQL parsing.
Hi Tal,

Adding "that" after the text "SQL Command" is changing the statement. We are not parsing any SQL statement only Guardium will parse. I have made the minor change in the text please have a look.

Thanks,
Subrato.

2023-09-27 14:28 UTC, merged