Added Azure Cosmos Connector
IBM/universal-connectors pull request #394
Opened 2023-10-31 11:30 UTC by BalramVerma1

2023-10-31 16:08 UTC, AlexaNahum approved these changes

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +2. Write the SQL query and select Execute Query.
```suggestion
2. Write the SQL query and click **Execute Query**.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +   - ServerIP : field is populated with 0.0.0.0, as this information is not embedded in the messages pulled from Azure.
```suggestion
   - ServerIP : this field is populated with 0.0.0.0, as this information is not embedded in the messages pulled from Azure.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +   - dbUser : field is populated with NA, as it is not available in ControlPlaneRequest, QueryRuntimeStatistics logs.
```suggestion
   - dbUser : this field is populated with NA, as it is not available in ControlPlaneRequest, QueryRuntimeStatistics logs.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +   - Exception > sqlString : field is populated with NA, as it is not available in Error logs.
```suggestion
   - Exception > sqlString : this field is populated with NA, as it is not available in Error logs.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +2. Logs will not capture for Failed login attempts.
```suggestion
2. Logs are not captured for failed login attempts.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +3. For DataPlaneRequest dbUser is NA when AADPrincipalId is Empty.
```suggestion
3. For DataPlaneRequest, dbUser is NA when AADPrincipalId is empty.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +4. Data Explorer and CLI doesn't support Creation, Updation and Deletion for User and Permission Operations; only the REST API does.
```suggestion
4. Data Explorer and CLI don't support creation, updating, and deletion for user and permission operations; only the REST API does.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +5. REST API doesn't support Creation, Updation and Deletion for Role Definition and Role Assignment Operations; But the Data Explorer and CLI does.
```suggestion
5. REST API doesn't support creation, updating, and deletion for role definition and role assignment operations; But the Data Explorer and CLI does.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +6. Data Explorer, CLI and REST API doesn't support Trigger execution; It can only be called via programs.
```suggestion
6. Data Explorer, CLI and REST API don't support trigger execution; It can only be called via programs.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +2. Enable the connector if it is already disabled, before proceeding uploading of the UC.
```suggestion
2. Enable the connector if it is disabled.
```

2023-10-31 16:08 UTC, AlexaNahum commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +    - Insert the Connection string in storage_connection from the Access Keys present in the Storage account from azure portal.
```suggestion
    - Insert the Connection string in storage_connection from the Access Keys present in the Storage account from the Azure portal.
```

2023-11-02 08:23 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +8. The "type" field should match in the input and filter configuration section. This field should be unique for every individual connector added.
Readme Changes Incorporated

2023-11-02 13:33 UTC, IBM-klahn commented
@AlexaNahum FYI - there's many flavors of Azure Cosmos DB: PostgreSQL, MongoDB, and Apache Cassandra
Does this plugin cover them all?  Or focus on one flavor in particular?

2023-11-03 06:09 UTC, BalramVerma1 commented
> @AlexaNahum FYI - there's many flavors of Azure Cosmos DB: PostgreSQL, MongoDB, and Apache Cassandra Does this plugin cover them all? Or focus on one flavor in particular?
> 
> @IBM-klahn I can't seem to leave a response but I can edit your comment so I'll do that. I don't 100% know the answer to that, the most I can give you is an educated guess. QA put this together and I just reviewed. Try asking @BalramVerma1 who opened this PR, or Ofer if he doesn't know.

@IBM-klahn we are focusing on one flavor that is Cosmos DB for NoSQL.

2023-11-03 11:31 UTC, apurva-birajdar commented on filter-plugin/logstash-filter-cosmos-azure-guardium/AzureCosmosOverAzureEventHub/filter.conf
this file is part of GI packaging ?
GI Folder structure looks incorrect to me, please recheck.

2023-11-03 11:44 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-cosmos-azure-guardium/AzureCosmosOverAzureEventHub/filter.conf
No, this file is not part of GI packaging

2023-11-09 05:34 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/AzureCosmosOverAzureEventHub/filter.conf
I would suggest to reach out to @RefaelAdi for the correct directory structure.

2023-11-09 05:47 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +			JsonObject properties=records.get(ApplicationConstants.PROPERTIES).getAsJsonObject();
I recommend to write a NullPointer check here, `records.get(ApplicationConstants.PROPERTIES) != null` or use of `Optional` will also work.

2023-11-09 05:49 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +			Integer hashcode=properties.get(ApplicationConstants.ACTIVITY_ID).getAsString().hashCode();
NullPointer check over `properties.get(ApplicationConstants.ACTIVITY_ID)`

2023-11-09 07:16 UTC, chirag-ibm requested changes

2023-11-09 07:16 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/SQLParser.java
> +
I would suggest to take this code of the lambda expression in different function. than call that function here (function as an argument). It will make easy to unit test that code.
Something like this,

```java
public <returnValue> functionName(<type> node, <type> level) {
    ....
    return <value>
}


ParseUtils.visitTree(result.parseTreeRoot, 
      (node, level) -> functionName(node, level));

```
with this way you can separately unit test the function.

2023-11-09 07:16 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/BasePegjsParser.java
> +	protected Rule parseRule(ParsingResult<?> result, Node<?> parent) {
I would suggest to split this function, This function is too lengthy.

2023-11-09 07:16 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegParser.java
> +import javax.json.JsonArray;
Use `Gson's` json.

2023-11-09 07:16 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegPegjsParser.java
> +import javax.json.Json;
use `Gson's` json.

2023-11-09 08:32 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/azure_cosmos.conf
> +input
Organise the indentations correctly for better readability.

2023-11-09 16:35 UTC, apurva-birajdar approved these changes

2023-11-10 08:15 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
> +	       - Select Connection string–primary key string from policy (it would be required in input plugin).
I am using the above one.

2023-11-10 11:28 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegPegjsParser.java
> +			System.out.print(level + " : ");
Why these output statement is written? Are they required? If not and are kept for the debugging, use Logger with the condition `logger.isDebugEnabled()`

2023-11-10 11:30 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegPegjsParser.java
> +		String input = "a = [abc0-9]";
What the "Main" function is doing here?

2023-11-10 11:31 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegPegjsParser.java
> +	public static void printTree(ParsingResult<?> result) {
`printTree` is called from the unwanted `Main` function. Is there any other use of this? If not, remove this.

2023-11-10 11:32 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegPegjsParser.java
> +	static {
remove this empty `static` blocks.

2023-11-10 11:32 UTC, chirag-ibm commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegPegjsParser.java
> +	static {
remove this empty `static` blocks.

2023-11-23 17:38 UTC, Tal-Daniel reviewed
Looks good, see if you can touch up minor comments, like indentation in conf file. Other comments should be taken seriously and followed-up for future plug-ins and post-release fixes. In brief: 

- GI package 
- consolidate to gson, instead of multiple json parsing libraries
- log event if log level is debug
- style and best practice comments like using stringBuffer or stringBuilder instead of string concatenations, clearer if code snippets, auto-formatting

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/azure_cosmos.conf
> +input
same as above.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/build.gradle
> +     implementation group: 'org.parboiled', name: 'parboiled-java', version: '1.1.8'
Cleared already.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/build.gradle
> +     implementation group: 'org.json', name: 'json', version: '20230227'
I agree that less dependencies are better. We'll take it as a guideline for next plug-ins.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/build.gradle
> +     implementation group: 'org.glassfish', name: 'javax.json', version: '1.1.4'
Agreed; taking it as a guideline for next plug-ins, and to examine as post-release.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/PegParser.java
> +import javax.json.JsonArray;
same as above; good guideline, and post-release.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/AzureCosmosOverAzureEventHub/filter.conf
GI support should be in place; post-release if not added.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +
I agree. post-release.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +			JsonObject properties=records.get(ApplicationConstants.PROPERTIES).getAsJsonObject();
Correct, though parser expects a certain audit log structure, and catch will inform of malformed input.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +			Integer hashcode=properties.get(ApplicationConstants.ACTIVITY_ID).getAsString().hashCode();
Correct, though parser expects a certain audit log structure, and catch will inform of malformed input. 
@BalramVerma1 if activityid appears in all logs, then OK, but consider.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +			record.setDbName(
I agree it's clearer; style comment. @BalramVerma1 please take not of this for next plug-ins, and in post-release of this plug-in.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +		fullsql = "{ \"time\": ".concat(records.get(ApplicationConstants.TIMESTAMP).toString())+","+"\"resourceId\": "+records.get("resourceId")+","+"\"category\": "+records.get(ApplicationConstants.CATEGO
A good practice, in general. @BalramVerma1 @sandeepkumarverma1 please take not for future plug-ins. affects performance.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/Parser.java
> +		JSONObject jsonObj = new JSONObject(jsonStr);
@BalramVerma1 @sandeepkumarverma1 I suggest for post-release to try consolidating as much as possible to gson as @chirag-ibm suggests.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/src/main/java/com/ibm/guardium/azure/cosmos/parser/BasePegjsParser.java
> +	protected Rule parseRule(ParsingResult<?> result, Node<?> parent) {
style comment, for next plug-ins.

2023-11-23 17:38 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-cosmos-azure-guardium/AzureCosmosOverAzureEventHub/filter.conf
> +filter
@BalramVerma1 please do try, carefully.

2023-11-29 17:34 UTC, Tal-Daniel approved these changes

2023-11-30 07:23 UTC, ofer-haim approved these changes

2023-11-30 07:23 UTC, merged