GRD-76588 feat: Dynamo DB plugin to be able to work using s3
IBM/universal-connectors pull request #396
Opened 2023-11-06 08:57 UTC by chirag-ibm

2023-11-06 09:15 UTC, ofer-haim requested changes
Please see my comments.
Also, need to verify the relevant zip file is entered to release-v1.5.1. @RefaelAdi can help with that

2023-11-06 09:15 UTC, ofer-haim commented on filter-plugin/logstash-filter-dynamodb-guardium/DynamodbOverCloudwatchPackage/DynamoDB/manifest.json
> +	"plugin_version": "0.0.1",
I guess it should be 1.0.1?

2023-11-06 09:15 UTC, ofer-haim commented on filter-plugin/logstash-filter-dynamodb-guardium/filter-test-generator.conf
> +        	"userIdentity": {
Please mask the fields in here...We should not enter values, even if they are just of test environments 
principalId": "<principal_Id>"
"accessKeyId": "<access_key_id>"
"arn":"<role_arn>"
"usrName":"<user_name>"

2023-11-06 09:15 UTC, ofer-haim commented on filter-plugin/logstash-filter-dynamodb-guardium/src/main/java/com/ibm/guardium/dynamodb/DynamodbGuardiumPluginFilter.java
> +// Copyright 2020-2021 IBM Inc. All rights reserved
Please update copyright statement

2023-11-06 09:33 UTC, chirag-ibm commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> -### Meet DynamoDB
I will write it for Dynamo but @RefaelAdi may put the information about the GI.

2023-11-06 09:39 UTC, AlexaNahum approved these changes

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +In the AWS web interface, configure the service for Dynamodb.
```suggestion
In the AWS web interface, configure the service for DynamoDB.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to https://console.aws.amazon.com/
```suggestion
1. Go to https://console.aws.amazon.com/.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. Click `Services` in the top left menu.
```suggestion
2. Click **Services**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +3. Underneath `All services`, click on `Database`.
```suggestion
3. Go to **All services** >  **Database**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +4. On the right panel, click `DynamoDB`.
```suggestion
4. Click **DynamoDB**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +5. At the top right, click on the dropdown menu and select your region.
```suggestion
5. Click the drop-down menu and select your region.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +6. Click the orange `Create Table` button.
```suggestion
6. Click **Create Table**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +9. Scroll down and click the orange `Create table` button.
```suggestion
9. Scroll down and click **Create table**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +There are different ways for auditing and logging. We will use CloudTrail for this example since it supports all required parameters. The below events are supported for auditing in AWS
```suggestion
There are different ways to audit and log events. We will use CloudTrail for this example since it supports all required parameters. The following events are supported for auditing in AWS:
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Click Services in the top left menu.
```suggestion
1. Click **Services**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. Underneath `All services`, click on `Management & Governance`.
```suggestion
2. Go to **All services** > **Management & Governance**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +3. On the right panel, click `Cloud Trail`.
```suggestion
3. Click **Cloud Trail**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +4. Click `Create trail` button.
```suggestion
4. Click **Create trail**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +5. Provide a trail name under `Trail name`.
```suggestion
5. Provide a trail name in the **Trail name** field.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +6. Under `Storage location`, verify "Create new S3 bucket" is selected.
```suggestion
6. For **Storage location**, verify that **Create new S3 bucket** is selected.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +7. Under `Log file SSE-KMS encryption`, uncheck the Enabled box.
```suggestion
7. In **Log file SSE-KMS encryption**, uncheck **Enabled**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +8. If the logs are to be monitored through CloudWatch, then forward them to Cloudwatch using steps 9 to 13. (If not, skip those steps).
```suggestion
8. If the logs are to be monitored through CloudWatch, then forward them to CloudWatch using steps 9 to 13. (If not, skip those steps).
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +9. Under **CloudWatch Logs**, check the **Enabled** box.
```suggestion
9. In **CloudWatch Logs**, check **Enabled**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Click the Service drop down.
```suggestion
1. Click the Service drop-down.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. On right `Recently visited` panel, click on CloudWatch.
```suggestion
2. In the **Recently visited** panel, click **CloudWatch**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +3. On the left panel, click on Logs.
```suggestion
3. Click **Logs** > **Log groups**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +4. Click on `Log groups` under Logs.
```suggestion

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +5. In the search box, enter the name of the log group created in the previous STEP 9.
```suggestion
5. In the search box, enter the name of the log group created previously in step 9.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +6. Click on the log group that appeared from the search.
```suggestion
6. Click on the log group that appears from the search.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +7. All logs will appear under log streams in the format: <account_id>_CloudTrail_<region>
```suggestion
7. All logs appear under log streams in this format: <account_id>_CloudTrail_<region>
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +## 4. Exporting Cloudwatch Logs to SQS using lambda function
```suggestion
## 4. Exporting CloudWatch logs to SQS using the lambda function
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +Cloudwatch to SQS.
```suggestion
CloudWatch to SQS.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +The SQS created in these steps will contain the messages to be filled up by the
```suggestion
The SQS created in these steps contain the messages to be filled up by the
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +lambda function (created in next section) in the queue by reading the CloudWatch logs.
```suggestion
lambda function (created in the next section) in the queue by reading the CloudWatch logs.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +The messages inside the SQS will contain content from CloudWatch logs.
```suggestion
The messages inside the SQS contain content from CloudWatch logs.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to https://console.aws.amazon.com/
```suggestion
1. Go to https://console.aws.amazon.com/.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. Click **Services**
```suggestion
2. Click **Services**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +3. Search for SQS and click on **Simple Queue Services**
```suggestion
3. Search for SQS and click **Simple Queue Services**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +6. Enter the name for the queue
```suggestion
6. Enter the name for the queue.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +7. Keep the rest of the default settings
```suggestion
7. Keep the rest of the default settings.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to https://console.aws.amazon.com/
```suggestion
1. Go to https://console.aws.amazon.com/.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +5. In the resources, specify the ARN of the queue created in the above step.
```suggestion
5. In the resources, specify the ARN of the queue created in the previous step.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +8. Assign the policy to the user
```suggestion
8. Assign the policy to the user:
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +    6. Click **Next: Review**
```suggestion
    6. Click **Next: Review**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +    7. Click **Add permissions**
```suggestion
    7. Click **Add permissions**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +The Lambda function will read the CloudWatch Logs and send the events into the SQS queue.
```suggestion
The lambda function will read the CloudWatch logs and send the events into the SQS queue.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +### Creating the Lambda function
```suggestion
### Creating the lambda function
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +Follow the steps below to configure the Lambda function.
```suggestion
Follow the steps in the next section to configure the lambda function.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +#### Creating IAM Role
```suggestion
#### Creating an IAM Role
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +Create the IAM role that will be used in the Lambda function setup. The AWS Lambda service will require permission to
```suggestion
Create the IAM role that will be used in the lambda function setup. The AWS Lambda service will require permission to
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to https://console.aws.amazon.com/
```suggestion
1. Go to https://console.aws.amazon.com/.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. Go to **IAM** -> **Roles**
```suggestion
2. Go to **IAM** > **Roles**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +3. Click **Create Role**
```suggestion
3. Click **Create Role**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +4. Under use case select **Lambda** and click **Next**
```suggestion
4. In **use case**, select **Lambda** and click **Next**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +5. Search for **AmazonSQSFullAccess** and select it
```suggestion
5. Search for **AmazonSQSFullAccess** and select it.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +6. Search for **CloudWatchLogsFullAccess** and select it
```suggestion
6. Search for **CloudWatchLogsFullAccess** and select it.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +7. Search for **CloudWatchEventsFullAccess** and select it
```suggestion
7. Search for **CloudWatchEventsFullAccess** and select it.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +8. Set the Role Name: e.g., "Export-Dynamo-CloudWatch-to-SQS-Lambda" and click **Create role**.
```suggestion
8. Set the role name: e.g., "Export-Dynamo-CloudWatch-to-SQS-Lambda" and click **Create role**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to https://console.aws.amazon.com/
```suggestion
1. Go to https://console.aws.amazon.com/.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +3. Click **Functions**
```suggestion
3. Click **Functions**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +4. Click **Create Function**
```suggestion
4. Click **Create Function**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +5. Keep **Author for Scratch** selected
```suggestion
5. Keep **Author for Scratch** selected.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +The Lambda will be called by a scheduler configured inside event rules in CloudWatch.
```suggestion
The lambda is called by a scheduler configured inside event rules in CloudWatch.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +4. Enter the name for the rule e.g., cloudwatchToSqs
```suggestion
4. Enter the name for the rule e.g., cloudwatchToSqs.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +12. Click Create Rule.
```suggestion
12. Click **Create Rule**.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +10. Select the lambda function created in the above step. e.g., Export-Dynamo-CloudWatch-Logs-To-SQS.
```suggestion
10. Select the lambda function created in the previous step. e.g., Export-Dynamo-CloudWatch-Logs-To-SQS.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +Before making any changes to the lambda function code, first disable the above rule.
```suggestion
Before making any changes to the lambda function code, first disable the rule discussed previously.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. The Dynamo DB plug-in does not support IPV6.
```suggestion
1. The DynamoDB plug-in does not support IPV6.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +## 4. Configuring the Dynamodb filters in Guardium
```suggestion
## 4. Configuring the DynamoDB filters in Guardium
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +• You must have LFD policy enabled on the collector. The detailed steps can be found in step 4 on [this page](https://www.ibm.com/docs/en/guardium/11.4?topic=dpi-installing-testing-filter-input-plug-
```suggestion
• Configure the policies you require. See ([policies](/docs/#policies)) for more information.

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +• Download the [cloudtrail_codec_plugin.zip](DynamodbOverCloudtrailPackage/DynamoDB/cloudtrail_codec_plugin.zip) plug-in, if the logs are to be pulled directly from CloudTrail.
```suggestion
• Download the [cloudtrail_codec_plugin.zip](DynamodbOverCloudtrailPackage/DynamoDB/cloudtrail_codec_plugin.zip) plug-in, if the logs are to be pulled directly from CloudTrail. (Do not unzip the offline-package file throughout the procedure). This step is not necessary for Guardium Data Protection v12.0 and later.

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +• Download the [logstash-filter-dynamodb_guardium_plugin_filter.zip plug-in.](./logstash-filter-dynamodb_guardium_plugin_filter.zip)
```suggestion
• Download the [logstash-filter-dynamodb_guardium_plugin_filter.zip plug-in](./logstash-filter-dynamodb_guardium_plugin_filter.zip). (Do not unzip the offline-package file throughout the procedure). This step is not necessary for Guardium Data Protection v12.0 and later.

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +• Download the [logstash-filter-dynamodb_guardium_plugin_filter.zip plug-in.](./logstash-filter-dynamodb_guardium_plugin_filter.zip)
Please work off the latest updated plug-ins from our Github site when creating new readmes. Many edits and additions have been made over time.

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. Enable the connector if it is already disabled, before proceeding to upload the UC.
```suggestion
2. Enable the connector if it is disabled.
```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +      plug-in. After it is uploaded, click **OK**.
```suggestion
      plug-in. After it is uploaded, click **OK**. This step is not necessary for Guardium Data Protection v12.0 and later.

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +      plug-in. After it is uploaded, click **OK**.
```suggestion
      plug-in. After it is uploaded, click **OK**. This step is not necessary for Guardium Data Protection v12.0 and later.

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +      plug-in. After it is uploaded, click **OK**.
```suggestion
      plug-in. After it is uploaded, click **OK**. This step is not necessary for Guardium Data Protection v12.0 and later.

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +      plug-in. After it is uploaded, click **OK**.
```suggestion
      plug-in. After it is uploaded, click **OK**. This step is not necessary for Guardium Data Protection v12.0 and later.

```

2023-11-06 09:39 UTC, AlexaNahum commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +## Configuring the dynamodb filters in Guardium Insights
```suggestion
## Configuring the DynamoDB filters in Guardium Insights
```

2023-11-06 10:03 UTC, RefaelAdi reviewed
I see 3 times the logstash-filter-dynamodb_guardium_plugin_filter.zip file under each package dir, are these the same? if they are, we don't need the same file 3 times

2023-11-06 11:06 UTC, apurva-birajdar reviewed
@chirag-ibm 
GRD-70191 [Implement cloudwatch to SQS flow for AWS Redshif]  is this tested ?

2023-11-06 14:38 UTC, ofer-haim commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +        * S3 (pull)
S3 input plugin is not supported in GI yet. Need to be clear that only Cloudwatch and SQS are relevant for GI

2023-11-06 14:38 UTC, ofer-haim commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +        * S3 (pull)
S3 input plugin is not supported in GI yet. Need to be clear that only Cloudwatch and SQS are relevant for GI

2023-11-06 14:38 UTC, ofer-haim commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +        * ClouedWatch (pull)
CloudWatch

2023-11-06 14:39 UTC, AlexaNahum approved these changes

2023-11-06 16:05 UTC, ofer-haim approved these changes
Please wait to get an answer reg. SQS tests before merge

2023-11-07 06:31 UTC, ofer-haim approved these changes

2023-11-07 07:05 UTC, RefaelAdi approved these changes

2023-11-07 08:41 UTC, merged