Added Intersystems IRIS Connector
IBM/universal-connectors pull request #408
Opened 2023-12-01 06:45 UTC by BalramVerma1

2023-12-04 05:23 UTC, chirag-ibm requested changes
Consider all the points mentioned in the https://github.com/IBM/universal-connectors/pull/394

If they are planned post release, clone the Jira ticket of the older PR and get it assigned.

2023-12-05 05:57 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/IrisParser.java
> +public class IrisParser {
Hi Chirag, 
 
Yes you are right about core principals, but if you look at the other connectors and even the demo plugins in Connectors  documentation this has been kept static.  This might be  because connectors are expected to digest huge data and this approach might has been used to control the instance count. Request you to please check with Tal.
 
Demo Plugin - https://github.com/IBM/logstash-filter-mongodb-guardium/tree/master

2023-12-05 06:06 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/Parser.java
> +public class Parser {
Please have a look at the response above for similar comment

2023-12-05 06:14 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/IrisParser.java
> +		ParseUtils.visitTree(result.parseTreeRoot, (node, level) -> {
Hi Chirag,

Junit is written at connector level to validate the Object and Verb.. we are validating the response of parser code at connector side. We can  consider this if required for future connectors.

2023-12-05 06:15 UTC, sandeepkumarverma1 commented
> Consider all the points mentioned in the #394
> 
> If they are planned post release, clone the Jira ticket of the older PR and get it assigned.

Hi Chirag,

We had a discussion with Tal on this, since this connector was already in final round of testing when you have provided comment for https://github.com/IBM/universal-connectors/pull/394, we are also going to analyze it post release and make the required changes.

Please check with Tal for more detail.

2023-12-13 11:01 UTC, Tal-Daniel requested changes
See my comments (partial):

2023-12-13 11:01 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-intersystems-iris-guardium/README.md
> +### Create ubuntu 22.04 Instance using AWS EC2 instance
Is it mandatory? Consider mentioning it's only an example, and installation on on-prem Ubuntu system should be OK.

2023-12-13 11:27 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/IrisParser.java
> +		ParseUtils.visitTree(result.parseTreeRoot, (node, level) -> {
Hi Tal,

As we have mentioned it would be good to have, but our approach till now is to validate the functionality connector level because those are also Junits and serving the same purpose.
We can discuss about this for future connectors.

Thanks
Sandeep Verma

2023-12-13 12:03 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/README.md
> + 2. IP addresses are blank while executing queries using Management Portal.
In Guardium report  Source program & Client Hostname will always be blank. 
Regarding IP Addresses- we are giving an option to user to provide Server Ip through input configuration and same value populates in report. If user does not provide Server Ip it will take 0.0.0.0. 
-Client Ip will be 0.0.0.0 in case of management portal and through CLI and third party tool we get the desired Client Ip.

2023-12-13 12:16 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/README.md
> + 6. We have seen the error(Communication link failure: Connection refused) using AWS EC2 instance Ip inside UC input configuration, a restart may be required for UC to bypass a connection refused iss
Hi Tal,

Restart is not required for On-prem Ubuntu. Hence we did not mention in limitations.

2023-12-14 07:15 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/intersystems_iris.conf
> +        last_run_metadata_path => "./.example_logstash_jdbc_last_run"
Hi Tal,

I added placeholders where the value needs to be changed.

I also checked already published connectors which has JDBC input plugin(https://github.com/IBM/universal-connectors/blob/main/filter-plugin/logstash-filter-azure-sql-guardium/azureSQLJDBC.conf) but did not find much comments there. Still I added few comments before some fields for better understanding.

This config file has the input and filter part in it. This file is needed to configure the connector as it fetches the data from the database and filters it.

2023-12-14 07:17 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/IntersystemsIrisoverJDBC/filter.conf
Hi Tal,

Indentation has been improved and regarding the requirement of this file please check above comment.

2023-12-14 07:18 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/README.md
> +### Create ubuntu 22.04 Instance using AWS EC2 instance
Hi Tal,

We have removed the specific version from the readme and replaced it with only Ubuntu.

2024-01-07 11:34 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/IrisParser.java
> +		ParseUtils.visitTree(result.parseTreeRoot, (node, level) -> {
Sandeep, please add the FIXME comment, as a signal for future committers; It has no effect on the functionality.

2024-01-07 11:41 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-intersystems-iris-guardium/build.gradle
> +    implementation group: 'org.glassfish', name: 'javax.json', version: '1.1.4'
Will be improved post-release. 
Resolving.

2024-01-07 11:44 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-intersystems-iris-guardium/intersystems_iris.conf
> +        last_run_metadata_path => "./.example_logstash_jdbc_last_run"
Thank you, Balram.

2024-01-07 11:45 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/IrisParser.java
> +public class IrisParser {
Will be examined for fix after release.

2024-01-07 11:46 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/Parser.java
> +public class Parser {
Will be examines and fixed after release.

2024-01-07 11:51 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-intersystems-iris-guardium/README.md
> +### Create ubuntu 22.04 Instance using AWS EC2 instance
Thank you. I meant that it should be clearer that the configuration is for Ubuntu instance, in general, and that this README and plug-in was developed and tested against an Ubuntu instance on AWS EC2, but any instance should work.

2024-01-08 06:26 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/src/main/java/com/ibm/guardium/intersystemsiris/IrisParser.java
> +		ParseUtils.visitTree(result.parseTreeRoot, (node, level) -> {
Hi Tal,
We have added the FIXME comment as a signal for future committers.

2024-01-08 06:29 UTC, BalramVerma1 commented on filter-plugin/logstash-filter-intersystems-iris-guardium/README.md
> +### Create ubuntu 22.04 Instance using AWS EC2 instance
Hi Tal,

We have added a line in README file as requested.

2024-01-08 09:38 UTC, merged