GCPMSSQLPublish
IBM/universal-connectors pull request #411
Opened 2023-12-06 12:46 UTC by apurva-birajdar

Publishing new UC MSSQL-GCP plugin with updated ReadMe.

2023-12-06 14:35 UTC, PratikshaSonawane approved these changes

2023-12-06 14:41 UTC, ofer-haim approved these changes
Please verify doc review before merge

2023-12-07 13:42 UTC, mllezak commented on filter-plugin/logstash-filter-mssql-guardium/AWSMSSQL_README.md
> +• You must have LFD policy enabled on the collector. The detailed steps can be found in step 4 on [this page](https://www.ibm.com/docs/en/guardium/11.4?topic=dpi-installing-testing-filter-input-plug-
This link is no longer available (we moved all of the Universal Connector doc to GitHub). Replace this sentence with:

Configure any policies that you need. The log full details policy is required.  See [policies](https://github.com/IBM/universal-connectors/tree/main/docs#policies) for more information.

2023-12-07 13:50 UTC, mllezak commented on filter-plugin/logstash-filter-mssql-guardium/AWSMSSQL_README.md
> +	Note :
Change to second bullet -- I think that's what you mean? But do make sure!

**Notes:" 
• For Guardium Data Protection 11.3, add the following line to the input section:
			'jdbc_driver_library => "${THIRD_PARTY_PATH}/mssql-jdbc-7.4.1.jre8.jar"'
*  If you configured auditing in an earlier version of Guardium Data Protection and then configure the universal connector later,  the universal connector processes the older records (that were previously audited) as well as new records.

2023-12-07 13:58 UTC, mllezak requested changes
There are a handful of changes that I'm requesting, but all in all, it looks good.

2023-12-08 06:54 UTC, apurva-birajdar commented on filter-plugin/logstash-filter-mssql-guardium/AWSMSSQL_README.md
> +	Note :
it should be in both .
AWS and GCP.

2023-12-12 13:54 UTC, mllezak approved these changes
Looks good.

2023-12-12 16:19 UTC, merged