GRD-78739: fix broken links and references
IBM/universal-connectors pull request #419
Opened 2024-01-10 10:16 UTC by ofer-haim

2024-01-11 20:09 UTC, mllezak commented on docs/readme.md
> +To prevent this default behavior and ensure efficient operation, it is recommended to configure these mechanisms as part of the input scope in the configuration file of the installed connector. You c
You kind of start in the middle (what's this default behavior?) 

Does this work better?

To ensure efficient operation, Guardium recommends that you configure load-balancing and failover as part of the input scope in the configuration file of the installed connector. You can either configure load-balancing through pull (Pub/Sub[^5.1], JDBC[^5.2], SQS[^5.3]) or push (Filebeat[^5.4]) methods.

2024-01-11 20:12 UTC, mllezak requested changes
I added a couple of comment to the Enabling load balancing and failover section.

Question -- Can we just rename that section:

## Enabling load balancing

2024-01-14 07:09 UTC, ofer-haim commented on docs/readme.md
> +To prevent this default behavior and ensure efficient operation, it is recommended to configure these mechanisms as part of the input scope in the configuration file of the installed connector. You c
I added a missing sentence in the beginning. Please let me know if you think I should keep it this way, or change the phrasing to be as you suggest here.

2024-01-16 14:01 UTC, RefaelAdi approved these changes

2024-01-16 16:33 UTC, natalygmkibm approved these changes

2024-01-16 16:38 UTC, merged