feat: GRD-70189 Supporting SQS input in AWS Dynamo DB filter plugin.
IBM/universal-connectors pull request #428
Opened 2024-02-01 09:22 UTC by chirag-ibm

[GRD-70189](https://jira-ds.rtp.raleigh.ibm.com:8443/browse/GRD-70189)
This PR includes the code changes required to support the logs pull of AWS Dynamo DB through the AWS SQS. In summary it covers,

Modifications in the backend java code and hence in the Zip package.
New configurations example which uses Logstash SQS input.
New points in added in the README documentation that explains the procedures of setting up Lambda functions and creating the SQS.

2024-02-01 09:44 UTC, PratikshaSonawane approved these changes

2024-02-01 16:02 UTC, ofer-haim approved these changes
Please do another quick review to verify it's the exact same change as verified by QA before merge

2024-02-05 16:46 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/CHANGELOG.md
> +- Support of SQS input. The plugin will be able to read and process the Dynamo DB
Support of Simple Queue Service (SQS) input. This plugin can read and process the DynamoDB

2024-02-05 16:48 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +    * Guardium Data Protection: 11.4 and above
11.4 and later.

2024-02-05 17:06 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +The SQS created in these steps will contain the messages to be filled up by the
I don't quite understand -- is this clearer?

The SQS that you create contains messages that will be filled by the Lambda function (see [Creating the Lambda function](Creating the Lambda function)) by reading the CloudWatch logs.

2024-02-05 17:07 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +#### Creating IAM Role
Create the IAM Role

2024-02-05 17:10 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +#### Create the lambda function
Create the Lambda function

(Note -- I think AWS Lambda is capitalized -- we just need to be consistent).

2024-02-05 17:15 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to https://console.aws.amazon.com/
Suggestion for all of the procedures where the first steps is Go to https://console.aws.amazon.com/...

Fold step 1 and step 2 into a single step, for example: 

1. From https://console.aws.amazon.com/, click **Services**.

Or 

1. From https://console.aws.amazon.com/, browse to **IAM** -> **Roles**.

2024-02-05 17:16 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +#### Automating the lambda function
#### Automate the Lambda function

2024-02-05 17:16 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to the CloudWatch dashboard.
From the CloudWatch dashboard, browse to **Events** > **Rules**.

2024-02-05 17:18 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +   This value must match the time specified in the lambda function code that calculates the time delta.
**Note:** This value must match the time that is specified in the Lambda function code that calculates the time delta. (For example, if the function code is set to 2 minutes, set the rate to 2 minutes.)

8. Click **Next**.

2024-02-05 17:22 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +  that the data being read by the Lambda Function would be large. In such cases the `timeout` parameter
that a large amount of data will be read by the Lambda function. In this case you might need to tune the `timeout` and `memory` parameters.

2024-02-05 17:23 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. The Dynamo DB plug-in does not support IPV6.
DynamoDB -- always one word.

2024-02-05 17:24 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. Enable the connector if it is already disabled, before proceeding to upload the UC.
Before uploading the Universal Connector, make sure that it is enabled.

2024-02-05 17:25 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +       This step is not necessary for Guardium Data Protection v12.0 and later.
**Note:** This step is not necessary for Guardium Data Protection 12.0 or later.

2024-02-05 17:26 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +       file. More details on how to configure the relevant input plug-in can be found [here](../../input-plugin/logstash-input-cloudwatch-logs/README.md).
For more details about configuring the relevent input plugin, see ....

2024-02-05 17:30 UTC, mllezak requested changes
Some general comments:

Make sure  that you use consistent capitalization and spelling: 

* Lambda function
* DynamoDB

Line 95, I didn't understand what you meant -- I tried to rewrite it, but I might not understand enough. 

Line 111, see my suggestion about folding steps 1 and 2 together -- this is a very long README and there are a lot of steps -- if we can remove one step for each procedure, it's just a little easier to read.

2024-02-06 07:57 UTC, chirag-ibm commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
>  There are different ways to audit and log events. We will use CloudTrail for this example since it supports all required parameters. The following events are supported for auditing in AWS:
I think this text is getting carried forward, Right now we almost support all the Events which are falling under Dynamo DB specific events. I will remove this line.

2024-02-06 08:05 UTC, chirag-ibm commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +The SQS created in these steps will contain the messages to be filled up by the
Agreed, The new content is clearer.

2024-02-06 14:18 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +* Before making any changes to the Lambda function code, first disable the above rule.
Before you make changes to the Lambda function code, disable the rule that you just created.

2024-02-06 14:20 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +3. The following fields couldn't be mapped with the Dynamo audit logs,
The `Client HostName` field cannot be mapped with the DynamoDB audit logs, Set this field to *NA*.

2024-02-06 14:26 UTC, mllezak approved these changes
I had just a few more comments. I approve after those are made.

2024-02-12 15:52 UTC, mllezak approved these changes
Nothing terrible here -- just some more cleanup (and trying to shorten the number of steps in some of the longer procedures).

Approved with changes.

2024-02-12 15:52 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
>  8. If the logs are to be monitored through CloudWatch, then forward them to CloudWatch using steps 9 to 13. (If not, skip those steps).
8. To monitor the logs through CloudWatch, take the following steps to forward them to Cloudwatch:
   1. Under **CloudWatch Logs**, check **Enabled**.
   2. Verify that **New** is selected for **Log group**.
   3. Under **Log group name**, provide a new log group name.
   4. Verify that **New** is selected for **IAM Role**.
   5. For **Role name**, provide a new role name.

2024-02-12 15:52 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +5. Enter the name for the queue
Add a period after steps 5 and 6.

2024-02-12 15:52 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +1. Go to https://console.aws.amazon.com/
1. From https://console.aws.amazon.com/, browse to  **IAM** -> **Roles**.

2024-02-12 15:52 UTC, mllezak commented on filter-plugin/logstash-filter-dynamodb-guardium/README.md
> +2. Go to **IAM** -> **Roles**
delete step 2.

2024-02-13 08:17 UTC, merged