fix: GRD-77625 Mongo Atlas Input Plugin.
IBM/universal-connectors pull request #429
Opened 2024-02-02 10:14 UTC by chirag-ibm

[GRD-77625](https://jira-ds.rtp.raleigh.ibm.com:8443/browse/GRD-77625)

This PR includes fixes in Mongo Atlas input plugin.

2024-02-02 10:59 UTC, apurva-birajdar approved these changes

2024-02-02 11:07 UTC, PratikshaSonawane approved these changes

2024-02-05 14:01 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
>      * Guardium Data Protection: 11.4 and above
11.4 and later.

2024-02-05 14:03 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
>  In order to support a few features one zip has to be added with the name "guardium_logstash-offline-plugins-mongo-atlas.zip".
To support Universal Connector features for MongoDB Atlas, add the ZIP file *guardium_logstash-offline-plugins-mongo-atlas.zip*.

2024-02-05 14:04 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +3. If 'Build a cluster' option is unavailable,
If 'Build a cluster' is not available, you need to create and provision a new cluster, as follows:

2024-02-05 14:05 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +   Now that your cluster is provisioned.
Your cluster is now provisioned.

2024-02-05 16:27 UTC, mllezak requested changes
I made a bunch of small updates -- please let me know if you have questions.

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +14. Select the project from the top left corner
Select the Project from the list below *Organizations*.

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +15. In the Security section of the left navigation, click on **Network Access**.
In the Security section, click **Network Access**.

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +3. Paste below text and click **Save**.
Paste the following code and then click **Save**.

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +    4. Click on the three dots right by the name of the selected project in the
Click the ellipses (...) next to the name of the selected project

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +4. Click on three dots adjacent to the Project selection menu
Click the ellipses (...) next to the Project menu (in the top left corner below the Organization menu).

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +    3. There will be a panel named **Region**.
From the **Region** panel, select any shard. After you select the shard, the **Status** page displays.

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +    5. You will land to the **Status** page.
6. On the *Status* page, the page title includes <hostname>:<port>. The host name format is:

   ```
   <cluster-name>-<shard-seq-seq>.<identifier>.mongodb.net
   ```
   For example: 
   ```
   cluster2-shard-00-01.i2jq9.mongodb.net
   ```

2024-02-05 16:27 UTC, mllezak commented on input-plugin/logstash-input-mongo-atlas/README.md
> +#### Mongo  event
#### Mongo event

2024-02-06 14:52 UTC, mllezak reviewed
And -- there are a few sections where I can't edit (or leave a note): 


Line 81/135 (under Authorizing outgoing traffic from Mongo Atlas:

Change: 
 2. Issue these command:
    • grdapi add_domain_to_universal_connector_allowed_domains domain=cloud.mongodb.com

To: 
 2. Issue the following command:
    ```
   grdapi add_domain_to_universal_connector_allowed_domains domain=cloud.mongodb.com
   ```
Line 91/145

Change step 8 to:

Make sure that the `type` filed matches in both the input and filter configuration sectiosn. This field must be unique for every individual connector that you add.

Supported audit messages & commands notes (lines 120/287 to 122/289:

**Notes:**
* To make sure that events are handled properly, take the following steps:
   *  Set MongoDB access control, because messages with no users are removed.
   * Do not filter `authcheck` and `authenticate` events out of the MongoDB audit log messages.

Under Limitations (lines 136/303):

* `Client Host Name` is not supported. For system-generated queries, 'Server Host Name' and 'Client Host Name' are the same.
* IPv6 addresses are typically supported by the MongoDB and filter plug-ins. However, IPV6 is not fully supported by the Guardium pipeline.
* `Source Program` is left blank.
* Mentioning 'Audit filter criteria on MongoDB' captures all of the events. Set the audit filter criteria as needed to avoid unnecessary logs.


**** 
I'm fine after these changes are made.

2024-02-07 15:16 UTC, merged