Added ScyllaDB Connector
IBM/universal-connectors pull request #466
Opened 2024-03-29 06:46 UTC by soumalya2004

2024-05-23 10:50 UTC, PratikshaSonawane requested changes

2024-05-23 10:50 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-scylldb-guardium/src/main/java/com/ibm/guardium/scylladb/Constants.java
> +	public static final String NOT_AVAILABLE = "NA";
Please change the NOT_AVAILABLE value to N.A. Sniffer expects minimum of 4 chars value

2024-05-23 11:47 UTC, chirag-ibm approved these changes

2024-05-23 13:13 UTC, apurva-birajdar approved these changes

2024-05-24 07:02 UTC, SubratoP1 commented on filter-plugin/logstash-filter-scylldb-guardium/src/main/java/com/ibm/guardium/scylladb/Constants.java
> +	public static final String NOT_AVAILABLE = "NA";
Hi Pratiksha,

We are already through with the multple round of UAT and no issue has been observed due to this value The same value has been used in the previous connectors. Even in the code review phase same value was there.

Making any change now wll initiate the testing again, Since this has no impact, its better not to touch code base.

Please let us know if you have any concern, we can discuss this over the call.

Thanks,
Subrato Pal

2024-05-27 05:37 UTC, PratikshaSonawane approved these changes

2024-05-27 06:03 UTC, merged