Elasticsearch connector
IBM/universal-connectors pull request #469
Opened 2024-04-01 05:24 UTC by AshishKumarShukla1

2024-04-01 05:41 UTC, chirag-ibm requested changes

2024-04-01 05:41 UTC, chirag-ibm commented on filter-plugin/logstash-filter-elasticsearch-guardium/elasticsearch-test.conf
> +  message =>'{"type":"audit", "timestamp":"2024-02-07T11:42:06,001+0530", "cluster.uuid":"Zm36-zi9T4-wNx6TyQ8NIA", "node.name":"node-1", "node.id":"TwCv5RHbR4ipCdYwZ1cefw", "host.name":"127.0.0.1", "
I would suggest to add the log lines for other scenarios too. This is just the example event of `authentication_success`.

2024-04-17 07:18 UTC, AshishKumarShukla1 commented on filter-plugin/logstash-filter-elasticsearch-guardium/elasticsearch-test.conf
> +  message =>'{"type":"audit", "timestamp":"2024-02-07T11:42:06,001+0530", "cluster.uuid":"Zm36-zi9T4-wNx6TyQ8NIA", "node.name":"node-1", "node.id":"TwCv5RHbR4ipCdYwZ1cefw", "host.name":"127.0.0.1", "
Added the log lines for other scenarios. Please have a look the changes.

2024-04-22 06:44 UTC, chirag-ibm approved these changes

2024-04-23 04:47 UTC, PratikshaSonawane requested changes

2024-04-23 04:47 UTC, PratikshaSonawane commented on docs/available_plugins.md
> +* [Elasticsearch](../filter-plugin/logstash-filter-elasticsearch-guardium/README.md)
This has to be added alphabetically. Please re-arrange

2024-04-23 04:47 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-elasticsearch-guardium/elasticsearch-test.conf
> +input {
Add copyright information at the top.

2024-04-23 04:47 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-elasticsearch-guardium/elasticsearch.conf
> +input {
Add copyright information

2024-04-23 05:27 UTC, AshishKumarShukla1 commented on filter-plugin/logstash-filter-elasticsearch-guardium/elasticsearch.conf
> +input {
added copyright information, please have a look the changes.

2024-04-23 05:27 UTC, AshishKumarShukla1 commented on filter-plugin/logstash-filter-elasticsearch-guardium/elasticsearch-test.conf
> +input {
added copyright information, please have a look the changes.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +5. Below are few sample sql queries example executing through sql cli .
remove numbering.
A few sample SQL queries that can be run with the SQL CLI are provided below.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +   select  * from hcltestingteam;
check space and use triple-backticks for all commands.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +  Note: Using  sql cli  user can execute only sql queries.
Using SQL CLI, you can only run the SQL type of queries.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +## 4. Query Execution using CURL command
Preferable: Running queries by using CURL command

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +User can execute any type of elasticsearch supported queries using curl commands. Below are  the few sample queries executed through curl command.
You* can
Check for extra spaces.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +User can execute any type of elasticsearch supported queries using curl commands. Below are  the few sample queries executed through curl command.
sue back-ticks

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +## 5. Viewing the Audit logs
Viewing the audit logs

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> + 1. User can see Audit log file in log directory with name
These should not be steps but bullet points.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> + 1. User can see Audit log file in log directory with name
Use back-ticks, check for extra spaces

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +To use Logstash to perform additional processing on the data collected by Filebeat, we need to configure Filebeat to use Logstash. To do this, modify the filebeat.yml file which you can find inside t
remove we need to

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +1. The following important fields couldn't be mapped with Elasticsearch audit logs:
he following important fields are not mapped with the Elasticsearch audit logs:

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +2. User can perform crud operation only through rest api,It can not be able to perform with sql cli.
You can perform crud operations only using the REST API.   

It can not be able to perform with sql cli?? I not sure of the meaning of this sentence. Please reframe.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +  Query 1:
remove your name, use dummy names/characters.

2024-04-23 07:23 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-elasticsearch-guardium/README.md
> +  Query 1:
remove username password instead use <username:password> and add note that it needs to be updated.

2024-04-23 12:03 UTC, AshishKumarShukla1 commented
all suggested read me changes are done.

2024-04-23 12:42 UTC, ShalakaKulkarni15 approved these changes

2024-04-23 13:03 UTC, merged