Publish first uc plugins
IBM/universal-connectors pull request #5
Opened 2021-08-10 09:27 UTC by ofer-haim

**Solution Descrition:**

Added plugins for MongoDB, S3, MySQL and HDFS, and changed readme files and relevant scripts accordingly

**Author:**
Ofer Haim, Guardium

2021-08-10 12:26 UTC, devanshah2 requested changes
Please remove all gradle build files such as .bin, .lock, .class, etc.. Should not upload any compoled code or .gradle folders. 

Should also add all these into .gitignore so that they do not show up in the git commit tree at all.

2021-08-10 12:26 UTC, devanshah2 commented on .github/CODEOWNERS
> +*       @devans @gdiamant @TALDAN @ITAIG @Ofer-Haim @Nataliya-Geimakher @Racheli-Aizik @Refael-Adi @GUYGA
@ofer-haim This one needs to be adjusted to use the public github usernames or it will not work. 

All the extra people you are adding need to have a github public account and use their public github IDs here instead.

2021-08-10 12:26 UTC, devanshah2 commented on .whitesource
> +  "settingsInheritedFrom": "whitesource-config/whitesource-config@master"
This is an internal files should not go public

2021-08-10 12:26 UTC, devanshah2 commented on common/.gradle/buildOutputCleanup/cache.properties
> +#Wed Jul 21 17:54:23 IDT 2021
All thye .lock, .bin files under .gradle should be removed all these are generated files.

2021-08-10 12:39 UTC, ofer-haim commented on .whitesource
> +  "settingsInheritedFrom": "whitesource-config/whitesource-config@master"
done

2021-08-10 12:42 UTC, ofer-haim commented on .github/CODEOWNERS
> +*       @devans @gdiamant @TALDAN @ITAIG @Ofer-Haim @Nataliya-Geimakher @Racheli-Aizik @Refael-Adi @GUYGA
Only adding myself for now. Will add the team once they have public Github account with IBM mail

2021-08-10 12:50 UTC, ofer-haim commented on common/.gradle/buildOutputCleanup/cache.properties
> +#Wed Jul 21 17:54:23 IDT 2021
done

2021-08-10 13:09 UTC, IBM-klahn commented
S3 readme doesn't indicate what input plugins are supported: filter-plugin/logstash-filter-s3-guardium/README.md

2021-08-10 13:14 UTC, IBM-klahn commented on README.md
> +An important note: only the plug-ins which appear in verifiedUCPlugins.txt are supported in Guardium Insights. The rest are only supported in Guardium GDP.
"Guardium Data Protection" instead of Guardium GDP (which translates to Guardium Guardium Data Protection).

2021-08-10 13:27 UTC, ofer-haim commented on filter-plugin/logstash-filter-s3-guardium/README.md
> +
sure

2021-08-10 13:28 UTC, ofer-haim commented on README.md
> +An important note: only the plug-ins which appear in verifiedUCPlugins.txt are supported in Guardium Insights. The rest are only supported in Guardium GDP.
done. Thanks

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-hdfs-guardium/LICENSE
> +   Copyright 2020 Elastic and contributors
any reason to change this copyright?

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-hdfs-guardium/wicked_cli.log
> +{"level":"debug","message":"CLI Functions: resetting CLI state","timestamp":"2021-07-21T15:03:53.956Z"}
this file should be removed.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-mysql-guardium/src/main/java/org/logstashplugins/MySqlFilterGuardium.java
> +package org.logstashplugins;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-mysql-guardium/src/test/java/org/logstashplugins/MySqlFilterGuardiumTest.java
> +package org.logstashplugins;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/main/java/com/ibm/guardium/s3/Parser.java
> +package com.ibm.guardium.s3;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/main/java/org/logstashplugins/LogstashFilterS3Guardium.java
> +package org.logstashplugins;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/test/java/com/ibm/guardium/ParserTest.java
> +package com.ibm.guardium;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/test/java/com/ibm/guardium/SampledEventsTest.java
> +package com.ibm.guardium;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/test/java/com/ibm/guardium/s3/AppUserNameTest.java
> +package com.ibm.guardium.s3;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/test/java/com/ibm/guardium/s3/UserAgentFieldsTest.java
> +package com.ibm.guardium.s3;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/test/java/com/ibm/guardium/samples/EventSamples.java
> +package com.ibm.guardium.samples;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on filter-plugin/logstash-filter-s3-guardium/src/test/java/org/logstashplugins/JavaFilterExampleTest.java
> +package org.logstashplugins;
missing copyright statement.

2021-08-10 14:13 UTC, devanshah2 commented on packagePluginsForGuardiumInsights.sh
> +#!/bin/bash
missing copyright statement.

2021-08-10 14:35 UTC, devanshah2 commented
Also make sure to follow https://github.com/IBM/universal-connectors/blob/main/CONTRIBUTING.md#legal to sign off on the pull request using the steps mentioned there

2021-08-10 15:18 UTC, ofer-haim commented on filter-plugin/logstash-filter-hdfs-guardium/LICENSE
> +   Copyright 2020 Elastic and contributors
returned to old version

2021-08-10 15:18 UTC, ofer-haim commented on filter-plugin/logstash-filter-hdfs-guardium/wicked_cli.log
> +{"level":"debug","message":"CLI Functions: resetting CLI state","timestamp":"2021-07-21T15:03:53.956Z"}
done

2021-08-10 16:41 UTC, devanshah2 commented on common/.gradle/buildOutputCleanup/cache.properties
> +#Wed Jul 21 17:54:23 IDT 2021
seems the file is still here.

2021-08-11 15:44 UTC, devanshah2 approved these changes

2021-08-11 15:44 UTC, merged