adding singlestore-filer-guardium
IBM/universal-connectors pull request #526
Opened 2024-07-12 14:34 UTC by hamidaamine

Hi

Adding singlestore-filer-guardium

Amine HAMIDA & Zineddine Gherrari

2024-07-15 05:35 UTC, chirag-ibm commented
@hamidaamine Please so remove the ".idea" directory. Since it is the IDE specific directory, not required to be committed. You may put it in the ".gitignore" list.

2024-07-15 05:39 UTC, chirag-ibm commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +# SingleStore-Guardium Logstash filter plug-in
@ShalakaKulkarni15, Please do review the README.

2024-07-15 05:44 UTC, chirag-ibm reviewed
Just need to remove the ".idea" directory

2024-07-15 08:37 UTC, ShalakaKulkarni15 requested changes
Please reach out to me for any clarification.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +    logs file are stored in auditlogsdir variable that can be retrieved using the following command
Use the following command to retrieve the log files that are stored in the auditlogsdir variable. 
```
SHOW GLOBAL VARIABLES LIKE 'audit%';
````
**Confirm the use of semi-colon.**

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +	If using docker deployment, the logs directory need to be persisted outside the container
Add this as note.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +	If using docker deployment, the logs directory need to be persisted outside the container
If you are using docker deployment, the logs directory must be present outside the container. 

Provide path of the directory as an example.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +## a. Filebeat installation
Heading 3 and update title as Installing Filebeat

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +### Procedure:
remove procedure

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +To install Filebeat on your system, follow the steps in this topic:
To install Filebeat on your system, refer to the [Filebeat quick start: installation and configuration](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#installation) topic.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +To use Logstash to perform additional processing on the data collected by Filebeat, we need to configure Filebeat to use Logstash. To do this, modify the filebeat.yml file which you can find inside t
To use Logstash to process additional data collected by Filebeat, configure Filebeat to use Logstash.  To do so, modify the **filebeat.yml** file 

**Note**: YSearch for the **filebeat.yml** file in the filebeat installation directory. You can also refer [Directory layout](https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.html) to search the **filebeat.yml** file.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +## b. Filebeat configuration:
Configuring Filebeat

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +### Procedure:
remove procedure heading

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +1. Configuring the input section :-
Update the **filebeat.inputs** section with the following parameters.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +	• Locate "filebeat.inputs" in the filebeat.yml file, then add the following parameters.
remove this line, write the parameters directly

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +	• Add the tags to uniquely identify the SingleStore events from the rest.
Use sub-steps. 
Add the following tag to identify the SingleStore events. 
```
tags : ["SingleStore"]
```

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +2. Configuring the output section:
remove colon, add full top

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +2. Configuring the output section:
Use sub-steps instead of bullet points

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +		• Locate "output" in the filebeat.yml file, then add the following parameters.
In the **output** section add the following parameters. 

Use sub-step for the parameters.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +
Add periods.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +#### For details on configuring Filebeat connection over SSL, refer [Configuring Filebeat to push logs to Guardium](https://github.com/IBM/universal-connectors/blob/main/input-plugin/logstash-input-b
Should be a note not a heading.
If it is important, add important note and highlight in bold.

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +## 5. Configuring the SingleStore filters in Guardium
Provide link to configuring Guardium .

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +• Configure the policies you require. See [policies](/docs/#policies) for more information.
Configure the required [policies](/docs/#policies).

2024-07-15 08:37 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +3. Click Upload File and select the offline [logstash-filter-singlestore_guardium_filter.zip](https://github.com/IBM/universal-connectors/releases/download/v1.5.1/logstash-filter-neodb_guardium_filte
says neodb in the link - please verify

2024-07-17 11:02 UTC, piyush-desai-ibm commented on filter-plugin/logstash-filter-singlestore-guardium/README.md
> +    logs file are stored in auditlogsdir variable that can be retrieved using the following command
It's SQL, the semicolon is needed.

2026-06-26 18:31 UTC, closed without merging