GRD-85034
IBM/universal-connectors pull request #537
Opened 2024-08-12 11:50 UTC by apurva-birajdar

2024-08-12 11:52 UTC, chirag-ibm approved these changes

2024-08-12 11:55 UTC, PratikshaSonawane requested changes

2024-08-12 11:55 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-aurora-mysql-guardium/auroraMysqlCloudwatch.conf
> +        #Unmask is an optional parameter. To get unmasked logs, you need to set unmask = true.
Please remove these lines this fix is yet to be tested

2024-08-12 11:56 UTC, ofer-haim commented
Shouldn't we upgrade the plugin version?

2024-08-12 12:08 UTC, apurva-birajdar commented on filter-plugin/logstash-filter-aurora-mysql-guardium/auroraMysqlCloudwatch.conf
> +        #Unmask is an optional parameter. To get unmasked logs, you need to set unmask = true.
done.

2024-08-12 12:22 UTC, apurva-birajdar commented
> Shouldn't we upgrade the plugin version?

Hi Ofer, We have not updated zip its just few checks that we added and removed the incorrect ones.

2024-08-13 05:09 UTC, PratikshaSonawane approved these changes

2024-08-13 06:11 UTC, merged