[GRD-80961,GRD-80162 and GRD-63127] Azure Postgres Publish new fixes
IBM/universal-connectors pull request #554
Opened 2024-08-22 09:19 UTC by apurva-birajdar

1. Updating conf
2. Updating ReadMe
3. Updating source code and zip

2024-08-22 09:23 UTC, ofer-haim commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> -### Meet Azure PostgreSQL
Why did you remove the Meet Azure part?

2024-08-22 12:06 UTC, apurva-birajdar commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> -### Meet Azure PostgreSQL
added

2024-08-22 12:13 UTC, ofer-haim commented
https://github.com/IBM/universal-connectors/tree/main/filter-plugin/logstash-filter-azure-postgresql-guardium#meet-azure-postgresql

2024-08-22 12:13 UTC, ofer-haim approved these changes

2024-08-23 09:55 UTC, ShalakaKulkarni15 requested changes

2024-08-23 09:55 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> +2. Click the search bar.
As discussed, check if these steps are required.

2024-08-23 09:55 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> +      1. In **Settings**, select **server parameters** and set the server parameters as follows:
Mentioned page name on which uses can see the settings options

2024-08-23 09:55 UTC, ShalakaKulkarni15 commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> +         timestamp, client ip, client port, database username, database name, process id, application name,sql state.
For information regarding timestamp, client ip, client port, database username, database name, process id, application name,sql state parameters, see [Error Reporting and Logging](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-LINE-PREFIX).

2024-08-24 05:46 UTC, apurva-birajdar commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> +For this plug-in, we used Azure Event Hub.
done

2024-08-27 04:46 UTC, apurva-birajdar commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> +2. Click the search bar.
As per your request removing first point where 'Procedure for DB creations' is mentioned to make it  compatible with other plugin's readMe.

2024-08-27 05:07 UTC, apurva-birajdar commented on filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
> +      1. In **Settings**, select **server parameters** and set the server parameters as follows:
done

2024-08-29 10:11 UTC, ShalakaKulkarni15 approved these changes

2024-08-30 09:02 UTC, merged