Generic plugin
IBM/universal-connectors pull request #60
Opened 2022-03-23 13:26 UTC by PratikshaSonawane

2022-03-23 16:21 UTC, raizik requested changes

2022-03-25 11:03 UTC, ofer-haim approved these changes

2022-03-29 14:06 UTC, itai-g-weather-com approved these changes

2022-03-29 14:09 UTC, natalygmkibm approved these changes

2022-03-29 14:22 UTC, ofer-haim commented on filter-plugin/logstash-filter-generic-guardium/GenericDBPackage/GenericDB/generic.conf
> +   if [type]=="test" {
@PratikshaSonawane as we agreed, we can merge this PR without this fix because we committed to a first version before the end of this quarter, but please open a JIRA story to address @raizik comment and improve it.

Performance and the appearance of our conf files are 2 of the most important considerations we have for UC plugins.

Racheli, if you agree with that approach please mark this request as resolved so we will be able to merge this PR

2022-03-29 15:10 UTC, merged