INS-48489 Bigtable filter plugin
IBM/universal-connectors pull request #609
Opened 2024-10-23 15:27 UTC by pankajkumaribm

2024-10-23 15:32 UTC, taees-eimouri approved these changes

2024-10-24 06:18 UTC, chirag-ibm approved these changes

2024-10-29 05:25 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses a GCP (Google Cloud Platform) event logs into
This statement is incorrect - As of now, the BigTable plug-in only supports Guardium Data Protection.
Change to - "The BigTable-Guardium Logstash filter plug-in supports Guardium Data Protection and Guardium Insights."

2024-10-29 05:28 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +This is a [Logstash](https://github.com/elastic/logstash) filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses a GCP (Google Cloud Platform) event logs into
Change "It parses a GCP (Google Cloud Platform) event logs into a Guardium record" to 
""It parses GCP (Google Cloud Platform) event logs into a Guardium record"

2024-10-29 05:39 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +This version is compliant with Guardium Data Protection v12.1 and above. Please refer to the [input plug-in repository](https://github.com/IBM/universal-connectors/tree/main/input-plugin/logstash-inp
Change "Please refer to the [input plug-in repository](https://github.com/IBM/universal-connectors/tree/main/input-plugin/logstash-input-google-pubsub) for more information." to
For more information, refer [input plug-in repository](https://github.com/IBM/universal-connectors/tree/main/input-plugin/logstash-input-google-pubsub).

2024-10-29 06:31 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +2. BigTable is automatically enabled in new projects. To activate BigTable in an existing project, enable the BigTable API.  Please refer to [Enable the BigTable API](https://console.cloud.google.com
Change "To activate BigTable in an existing project, enable the BigTable API.  Please refer to [Enable the BigTable API](https://console.cloud.google.com/marketplace/product/google/bigtable.googleapis.com) for more information." to
 "To activate BigTable in an existing project, refer Enable the BigTable API](https://console.cloud.google.com/marketplace/product/google/bigtable.googleapis.com).

2024-10-29 06:33 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +3. Create a BigTable instance that stores the data. Please refer to [Create a Dataset](https://cloud.google.com/bigtable/docs/creating-instance) for more information.
For more information, refer [Create a Dataset](https://cloud.google.com/bigtable/docs/creating-instance).

2024-10-29 06:33 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +4. Create a table. Please refer to [Create Table](https://cloud.google.com/bigtable/docs/samples/bigtable-hw-create-table) for more information.
For more information, refer  [Create Table](https://cloud.google.com/bigtable/docs/samples/bigtable-hw-create-table).

2024-10-29 06:33 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +5. Query table data. Please refer to [Query Table Data](https://cloud.google.com/bigquery/docs/external-data-bigtable) for more information.
For more information, refer [Query Table Data](https://cloud.google.com/bigquery/docs/external-data-bigtable)

2024-10-29 06:37 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +User can view and download the generated logs.
You can view and download the generated logs.
You need the following identity and access management roles to view and download the generated logs:
* View logs:
roles/logging.viewer (Logs Viewer) 
roles/logging.privateLogViewer (Private Logs Viewer)
* Download logs:
roles/logging.admin (Logging Admin)
roles/logging.viewAccessor (Logs View Accessor)

2024-10-29 08:46 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +### Create a topic in Pub/Sub
Can you change the topic title for task topics to use gerunds. For example: Creating a topic in Pub/Sub, Creating a subscription in Pub/Sub. Please make these changes for other topics In **Configuring BigTable on GCP**

2024-10-29 08:55 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +* You can filter the logs by log name, resource, and  severity.
Remove the bullet points for  You can filter the logs by log name, resource, and severity. Multi-region

2024-10-29 08:56 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +Multi-region
Can you filter logs by multi-region.
Then, change to - You can filter the logs by log name, resource, severity, and multi-region.

2024-10-29 08:56 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +* In cases of multiple regions, you need to do the same set of configurations per each region.
Remove the bullet point for this sentence.

2024-10-29 08:57 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +   2. The writer identity appears in the Sink details panel.
This is not a step. Remove the numbered list.

2024-10-29 09:00 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +   1. Add the sink's writer identity to topic >>>>
Why is period missing in all the steps?

2024-10-29 09:03 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +      - Click on SHOW INFO panel
Can we remove "on" and change to:
Click SHOW INFO panel.
Click ADD PRINCIPAL.

2024-10-29 09:05 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +* Go to the Service accounts section of the IAM & Admin console.
Change the bullet list to numbered list as they are to followed in a specific order.

2024-10-29 09:08 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +## 4. Limitations
Why is "Limitations" numbered "4" when none of the other topics are numbered

2024-10-29 09:14 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +  1. BigTableAudit - `ACTIVITY`, `DATA_ACCESS` logs
Do we need a numbered list. Can we change to bullet list.

2024-10-29 09:18 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +1. If no information regarding certain fields is available in the logs, those fields will not be mapped.
Change "If no information regarding certain fields is available in the logs, those fields will not be mapped" to
The fields whose information is not available in the logs are not mapped.

2024-10-29 09:21 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +8. Log messages have a size limit of 100K bytes
Period missing at the end of the sentence.

2024-10-29 09:22 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +9. The Audit/Data access log doesn't contain a server IP. The default value is set 0.0.0.0 and can be in IPV4 or IPV6 format.
Change to "The default value is set to 0.0.0.0 and can be in IPV4 or IPV6 format.

2024-10-29 09:26 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +11.  `serverHostName` pattern for BigTable GCP :
This does not look like a limitation. Is this sentence incomplete?

2024-10-29 09:29 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +13. Bigtable uses two different service names (`bigtable.googleapis.com` & `bigtableadmin.googleapis.com`) depending on the tasks being performed. This will result in two distinct S-TAP Host entries.
Change to - This results in two distinct S-TAP host entries.

2024-10-29 09:30 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +The inclusion filter mentioned above will be used to view the Audit logs in the GCP Logs Explorer.
Change to - The inclusion filter mentioned above is used to view the Audit logs in the GCP Logs Explorer.

2024-10-29 09:31 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +2. Exception object will be prepared based on severity of the logs.
Change to - Exception object is prepared based on severity of the logs.

2024-10-29 09:33 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +15. The BigTable audit log doesn’t include login failed logs, so these will not appear in the guardium LOGIN_FAILED report.
Change to - The BigTable audit log doesn’t include login failed logs. So, these logs do not appear in the Guardium LOGIN_FAILED report.

2024-10-29 09:34 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +1. On the collector, go to Setup > Tools and Views > Configure Universal Connector.
Change to - On the collector, go to ```Setup``` > ```Tools and Views``` > ```Configure Universal Connector```.

2024-10-29 09:35 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +3. Click Upload File and select the offline  [logstash-filter-big_table_guardium_filter](gdp-pubsub-bigtable-package/logstash-filter-big_table_guardium_filter.zip) plug-in. After it is uploaded, clic
Change to - Click  ```Upload File```

2024-10-29 09:36 UTC, VanajaGP commented on filter-plugin/logstash-filter-pubsub-bigtable-guardium/README.md
> +11. After the offline plug-in is installed and the configuration is uploaded and saved in the Guardium machine, restart the Universal Connector using the Disable/Enable button.
Change to ```Disable/Enable``` button.

2024-10-29 09:41 UTC, VanajaGP reviewed
Reviewed the readme. Reach out to me for any clarifications.

2024-11-07 16:51 UTC, VanajaGP commented
All changes look good.

2024-11-07 16:53 UTC, taees-eimouri approved these changes

2024-11-10 08:38 UTC, hadarkorny requested changes
Please check these tasks before merging this PR. 
- [x] Tested internal build script for offline packages. 

- [x] Documentation reviewed by @ShalakaKulkarni15.

2024-11-18 18:55 UTC, doryo approved these changes

2024-11-19 12:12 UTC, ShalakaKulkarni15 commented
@hadarkorny, @VanajaGP had already reviewed this PR in my absence.

2024-11-19 12:57 UTC, VanajaGP approved these changes
Changes look good

2024-11-19 14:44 UTC, pankajkumaribm commented
> Please check these tasks before merging this PR.
> 
> * [x]  Tested internal build script for offline packages. Tested
> * [x]  Documentation reviewed by @ShalakaKulkarni15.

2024-11-19 15:08 UTC, merged