Update README.md
IBM/universal-connectors pull request #62
Opened 2022-03-28 16:43 UTC by AlexaNahum

following patch request from Gene

2022-03-28 16:46 UTC, raizik approved these changes

2022-03-28 17:08 UTC, mae-rockar-ibm requested changes

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +The following arguments are used in configuration for OUA plugin
these arguments should be on separate lines instead of jammed together in one line

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +guardium/${OUA_USER_PASS}@<ORACLE_OUA_SERVER>:<ORACLE_PORT>/<SERVICE_NAME>" }
this should be in a code block

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +if [type] == "oua" { json { source => "message" } if "_jsonparsefailure" not in [tags] { oua_filter {} } }
this should be in a code block

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +'resolve'), principal_name => 'guardium', principal_type => xs_acl.ptype_db));
code block

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +SELECT UTL_INADDR.get_host_address FROM DUAL;
code block

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +2. Enable the universal collector feature on the designated Guardium collectors or the stand-alone system. See https://www.ibm.com/docs/en/guardium/11.4?topic=connector-enabling-guardium-universal-co
format link?

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +Note: In this release only specific Instant client will be supported from v21.1.0.0.0 Download here: https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-basic-21.
format link?

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +3. Download the OUA UC plugin "guardium-oua-uc.zip" from https://github.com/IBM/universal-connectors/raw/main/filter-plugin/logstash-filter-oua-guardium/OracleUnifiedAuditPackage/OracleUnifiedAudit/g
format link?

2022-03-28 17:08 UTC, mae-rockar-ibm commented on filter-plugin/logstash-filter-oua-guardium/README.md
> +• Type any unique name in the "Connector name" field
why is markdown's unordered list not being used for this?

2022-03-28 18:47 UTC, mae-rockar-ibm commented
[PR](https://github.com/AlexaNahum/universal-connectors/pull/1) to fix the issues found in my review

2022-03-29 06:59 UTC, ofer-haim approved these changes

2022-03-29 07:04 UTC, merged