Merge DocumentDB Plugin
IBM/universal-connectors pull request #82
Opened 2022-04-28 11:50 UTC by sandeepkumarverma1

Signed-off-by: Sandeep Kumar Verma1 <sandeep.kumar.verma1@ibm.com>

2022-05-01 07:42 UTC, Tal-Daniel requested changes
Thank you. Some general comments, in addition to the comments below: 

- See other filter plug-ins for the name of the folder with the offline package, and conform to it.
- Remove PPTX file. README should be used, for important texts
- Remove image.png (not used)
- remove build.gradle.bak, Parser.java.bak, if not needed, and other similar files. 
- gradle.properties is usually not included, and can be mentioned in README; compare with other plug-ins.

2022-05-01 07:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java.bak
> +		//record.getAccessor().setServiceName(dbName);
can be removed.

2022-05-01 07:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +		//record.getAccessor().setServiceName(SERVER_TYPE_STRING);
remove if not used

2022-05-01 07:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +
Minor: Repeating code here and in parseProfilerRecord() can be moved to a function.

2022-05-01 07:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +		accessor.setServiceName(SERVER_TYPE_STRING);
OK for now, though on cloud environments, and in general, _service name_ should be used to specify a higher hierarchy than the data source name, like the VM instance or container id that runs this server as well as datasource name. Think about it like the process that runs the data source name, and find a suitable text string to represent it. If not available, specify the data source name. In short, try to include in service name some hierarchy + the datasource name. Example: instanceID:project:dbname.

2022-05-01 07:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +* authCheck - Unauthorized attempts to perform an operation.
duplicate

2022-05-01 07:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +* Download the guardium_logstash-offline-plugin-documentdb.zip plug-in.
direct link, if possible

2022-05-01 07:42 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +This is a Logstash filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from the DocumentDB audit and profiler logs into a Guardium reco
Could you mention it currently supports only Guardium Data Protection?

2022-05-02 16:23 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/Offline_pack_with_logger/docdb.conf
> +replace => { "serverHostnamePrefix" => "<accountId>_%{[cloudwatch_logs][log_stream]}" }
Changes has been made in Readme.md file

2022-05-02 16:23 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/Offline_pack_with_logger/docdb.conf
> +secret_access_key => ****************************************
Done

2022-05-02 16:23 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/Offline_pack_with_logger/docdb.conf
> +secret_access_key => ****************************************
Done

2022-05-02 16:24 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/plugins/logstash-filter-documentdb_guardium_filter.gemspec
> +  s.email           = ['taldan@il.ibm.com']
Done

2022-05-02 16:24 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +
Since this is a minor change we will take care of it in future plugin.

2022-05-02 16:25 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +		accessor.setServiceName(SERVER_TYPE_STRING);
As you have suggested we will keep this in mind for future connectors

2022-05-02 16:25 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +* authCheck - Unauthorized attempts to perform an operation.
Duplicate entry removed from Readme.md file

2022-05-02 16:25 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +* Download the guardium_logstash-offline-plugin-documentdb.zip plug-in.
Done

2022-05-02 16:25 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +This is a Logstash filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from the DocumentDB audit and profiler logs into a Guardium reco
Done

2022-05-02 16:31 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilter.java
> +				 */
Done

2022-05-02 16:31 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java
> +		//record.getAccessor().setServiceName(SERVER_TYPE_STRING);
done

2022-05-02 16:31 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/Parser.java.bak
> +		//record.getAccessor().setServiceName(dbName);
done

2022-05-04 03:53 UTC, Tal-Daniel approved these changes

2022-05-04 03:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
>  1. On the collector, go to Setup > Tools and Views > Configure Universal Connector.
Could you link to the conf here as well, for easier access?

2022-05-04 03:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
>  input{
I liked the example version, without the placeholders, here. Consider linking to the conf, saying there are more details there. Another direction is just to link to the conf (no need to copy if exactly the same), explaining it's also required, apart from uploading the plug-in.

2022-05-04 03:53 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +    ```GUARDIUM_UNIVERSALCONNECTOR_COMMONS_PATH=../guardium-universalconnector-commons/build/libs```
I think you should also mention LOGSTASH_CORE_PATH that points to the logstash-core classes, as described in the How to write tutorial, linked below.

2022-05-04 04:00 UTC, Tal-Daniel commented
Sandeep, approved with comments. 
Could you also add to this PR an updated [available_plugins.md](../blob/main/docs/available_plugins.md)?

2022-05-04 04:45 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
>  1. On the collector, go to Setup > Tools and Views > Configure Universal Connector.
Done

2022-05-04 05:09 UTC, sandeepkumarverma1 commented
> Sandeep, approved with comments. Could you also add to this PR an updated [available_plugins.md](../blob/main/docs/available_plugins.md)?

Done Sir

2022-05-04 07:32 UTC, ofer-haim requested changes

2022-05-04 07:32 UTC, ofer-haim commented on docs/available_plugins.md
> +|            [DocumentDB](../filter-plugin/logstash-filter-documentdb-aws-guardium/README.md)            | 4.0        | Cloud                 | IBM                  | CloudWatch (pull)
Could you please change 'Cloud' to AWS?
I guess you used the same template as in Teradata but it's a bit different, since Teradata uses jdbc input plugin which works with all types of Cloud environment.

2022-05-04 07:32 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/DocumentDBOverCloudwatchPackage/sample_audit_log.txt
> +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Did you test samples with complex queries?

2022-05-04 07:32 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +# DocumentDB-Guardium Logstash filter plug-in
Was this reviewed by someone from documentation team?

2022-05-04 07:32 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
> +apply from: LOGSTASH_CORE_PATH + "/../rubyUtils.gradle"
Which Logstash version is this plugin based on?

2022-05-04 07:32 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/plugins/logstash-filter-documentdb_guardium_filter.gemspec
> +  s.authors         = ['IBM', 'Tal Daniel', 'Natali Geymakher']
description and authors shouldn't be Tal and Nataliya.
I think it should be 'HCL' without any mail for now

2022-05-04 07:32 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilter.java
> +/*
Looks ok to me. Did QA team verify this plugin?

2022-05-04 07:32 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/test/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilterTest.java
> +public class DocumentdbGuardiumFilterTest {
👍 👍

2022-05-04 07:41 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/test/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilterTest.java
> +public class DocumentdbGuardiumFilterTest {
Any Change Required here?

2022-05-04 07:41 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/main/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilter.java
> +/*
IBM UAT is done on this connector

2022-05-04 07:42 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/plugins/logstash-filter-documentdb_guardium_filter.gemspec
> +  s.authors         = ['IBM', 'Tal Daniel', 'Natali Geymakher']
We have removed it  based on the earlier PR review feedback from TAL.

2022-05-04 07:42 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
> +apply from: LOGSTASH_CORE_PATH + "/../rubyUtils.gradle"
7.14

2022-05-04 07:43 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +# DocumentDB-Guardium Logstash filter plug-in
Whos approval required on this?  Tal has already reviewed this PR.

2022-05-04 07:43 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/src/test/java/com/ibm/guardium/documentdb/DocumentdbGuardiumFilterTest.java
> +public class DocumentdbGuardiumFilterTest {
Looks very good TMHO

2022-05-04 07:44 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/DocumentDBOverCloudwatchPackage/sample_audit_log.txt
> +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Whole UAT is completed on this. This is just a sample log

2022-05-04 07:45 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
> +apply from: LOGSTASH_CORE_PATH + "/../rubyUtils.gradle"
I'd suggest to try using 7.16.2 or above from now on, but it's ok at the moment to publish with this version

2022-05-04 07:46 UTC, ofer-haim commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +# DocumentDB-Guardium Logstash filter plug-in
@Tal-Daniel we need to define who's responsible for validation this documentation

2022-05-08 14:22 UTC, Tal-Daniel approved these changes

2022-05-09 12:47 UTC, AlexaNahum requested changes
Reviewed the content per the team's request and found a few minor fixes to suggest

2022-05-09 12:47 UTC, AlexaNahum commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +2. Following important fields couldn't be mapped with DocumentDB audit/profiler logs
*The following

2022-05-09 12:47 UTC, AlexaNahum commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +2. Enter a name for e.g., GuardiumCloud9
Enter a name, for example GuardiumCloud9

2022-05-09 13:19 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
> +2. Following important fields couldn't be mapped with DocumentDB audit/profiler logs
Done please have a look

2022-05-10 08:19 UTC, merged