ADD MariaDB Plugin
IBM/universal-connectors pull request #90
Opened 2022-05-10 12:19 UTC by sandeepkumarverma1

Guardium MariaDB Plugin

2022-05-16 07:54 UTC, Tal-Daniel requested changes

2022-05-16 07:54 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +The Guardium universal connector is the Guardium entry point for native audit logs. The Guardium universal connector identifies and parses the received events, and converts them to a standard Guardiu
In this plug-in, I suggest to mention that Guardium sniffer also parses the SQL command/query.

2022-05-16 07:54 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +If you'd like to start with the most simple filter plugin, we recommend to follow all the steps in [How to write a Java filter plugin][logstash-java-plugin-dev] tutorial.
broken link (works above, though)

2022-05-16 08:25 UTC, ofer-haim commented on filter-plugin/logstash-filter-mariadb-guardium/src/main/java/com/ibm/guardium/mariadb/ParserHelper.java
> +					: ApplicationConstant.CLIENT_IP_STRING);
If I remember correctly, we could only extract server_ip from Filebeat

2022-05-16 08:31 UTC, ofer-haim commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/MariaDB.conf
> +input
Full configuration file should be on the upper level (filter-plugin/logstash-filter-mariadb-guardium/MariaDB.conf)

Inside filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage there should be only the filter section, called filter.conf, see [mongo](https://github.com/IBM/universal-connectors/blob/main/filter-plugin/logstash-filter-mongodb-guardium/MongodbOverFilebeatPackage_3.1/MongoDB/filter.conf) as an example

2022-05-16 08:31 UTC, ofer-haim commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/mariadb-test.conf
> +input {
This should also be in the parent directory (upper level)

2022-05-16 08:31 UTC, ofer-haim commented on filter-plugin/logstash-filter-mariadb-guardium/VERSION
> +2.3.60
Is this the version of the plugin, or the version of MariaDB you used for dev and test?

2022-05-16 08:31 UTC, ofer-haim commented on filter-plugin/logstash-filter-mariadb-guardium/build.gradle
> +    implementation group: 'commons-validator', name: 'commons-validator', version: '1.4.1'
I think it should be 1.5.1

2022-05-16 08:31 UTC, ofer-haim commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/sample_audit_log.log
> +20220121 11:12:26,ip-172-31-44-208.ap-south-1.compute.internal,root,localhost,21,0,CONNECT,,,0
This too should be in the parent directory

2022-05-16 14:02 UTC, PratikshaSonawane requested changes

2022-05-18 10:09 UTC, sandeepkumarverma1 commented
HI @Tal-Daniel ,

Can we ask Alexa to review the readme as well.as well?

2022-05-21 07:47 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/VERSION
> +2.3.60
yes this i mariaDB plugin version

2022-05-21 09:54 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +#### Guard Record Field
I think it has been added in multiple plugins . https://github.com/IBM/universal-connectors/tree/main/filter-plugin/logstash-filter-mysql-guardium
@Tal-Daniel  we need to design a template regarding what all should be added on Readme.md else it would be difficult to do back and forth after completion.

2022-05-21 09:56 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +	- ClientIP - Not avaiable in Audit Logs
Hi Tall,

We get hostname for serverhost and client in mariadb logs. Both fields has been mapped with the accessors properties serverHostName and clientHost.

Below is the sample log for your reference, 

20220518 19:50:02,**ip-172-31-44-208.ap-south-1.compute.internal,**root,**ip-172-31-10-59.ap-south-1.compute.internal**,15,69,QUERY,,'SELECT DATABASE()',0

2022-05-21 09:57 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/MariaDB.conf
> +grok { match => { "minutes" => "(?<offset_diff>[^[0-9]]*)%{GREEDYDATA:actual_minutes}" } }ruby { code => "event.set('minutes1', event.get('actual_minutes').to_i * 60)" }
The configuration has been taken from SAP Hana Plugin considering it has been tested and only acceptable format.  Internal code of time conversion is different based on our requirement.

2022-05-21 09:58 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/src/main/java/com/ibm/guardium/mariadb/ParserHelper.java
> +					: ApplicationConstant.CLIENT_IP_STRING);
ServverIP/hostname we can get through filebeat, this code for client ip might be initially added in code. I Will remove this segment in future CR for MariaDB. 
Just avoiding any code change as of now.

2022-05-21 10:01 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +The Guardium universal connector is the Guardium entry point for native audit logs. The Guardium universal connector identifies and parses the received events, and converts them to a standard Guardiu
Done

2022-05-21 10:01 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +If you'd like to start with the most simple filter plugin, we recommend to follow all the steps in [How to write a Java filter plugin][logstash-java-plugin-dev] tutorial.
Fixed

2022-05-21 10:01 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/MariaDB.conf
> +input
Done

2022-05-21 10:01 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/mariadb-test.conf
> +input {
Done

2022-05-21 10:02 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/build.gradle
> +    implementation group: 'commons-validator', name: 'commons-validator', version: '1.4.1'
We haven't received any guidelines for this library, so for making any change will impact dependency scan report as well as require another round of testing.

Leaving it as it is for now

2022-05-21 10:03 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/sample_audit_log.log
> +20220121 11:12:26,ip-172-31-44-208.ap-south-1.compute.internal,root,localhost,21,0,CONNECT,,,0
Done

2022-05-21 10:03 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +if [agent][type] == "filebeat" and "MariaDB_On_Premise" in [tags][0]{
Can you please suggest a plugin where it is mentioned already?  I will do the change accordingly.

2022-05-21 10:04 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +
Guardium Automatically enabled the connector if it is in disabled mode when we upload the connector, we don't have need to mentioned anything about it.
I haven't seen any one adding details regarding type field in Readme. Can you please share a link of connector where it is already mentioned?

2022-05-21 10:05 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/MariaDBOverFilebeatPackage/MariaDB.conf
> +  }
Done

2022-05-21 10:34 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/src/main/java/com/ibm/guardium/mariadb/MariadbGuardiumFilter.java
> +				|| event.getField(ApplicationConstant.OPERATION_KEY).toString().equals("DISCONNECT"))
Hi Tal, for connect property we are capturing failed_connect records because logs appearing with this connect property are not having any SQL details for example
**20220501 02:16:01,ip-172-31-44-208.ap-south-1.compute.internal,root,localhost,83,0,CONNECT,,,0**

For login failed we get this record which are mapped with Login_Failed Property.
**20220222 16:10:59,DESKTOP-10MCU7B,root,localhost,9,0,FAILED_CONNECT,,,1045**

2022-05-23 14:00 UTC, IBM-klahn submitted a review, later dismissed
Available Plugins page needs to be in alphabetical order.  Please don't just list it at the bottom of the list of plugins.

2022-05-26 08:06 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +
Yes it does, but there was one issue around this [GRD-55461], so post this, it was decided to add this in README, same is fixed in GRD-60211

2022-05-26 08:08 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +if [agent][type] == "filebeat" and "MariaDB_On_Premise" in [tags][0]{
EDB postgre has those details added.

2022-05-31 18:23 UTC, sandeepkumarverma1 commented
Hi @AlexaNahum ,

This is MariaDB plugin ready to be released on IBM Github. As suggested by @Tal-Daniel  request you to please have a look at readme.md file and provide your feedback.

Thanks
Sandeep Verma

2022-06-01 06:51 UTC, sandeepkumarverma1 commented
> Sure @sandeepkumarverma1 . Any specific section I should focus on? I'm seeing a lot of code..

Just Readme.md,any suggestion.

2022-06-01 06:52 UTC, AlexaNahum approved these changes
Done. A few minor suggestions that I added as in-line comments.

2022-06-01 06:52 UTC, AlexaNahum commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +2. Enable the connector if is in disabled state before uploading the UC plug-in.
Enable the connector if it is disabled before uploading the UC plug-in.

2022-06-01 07:20 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +2. Enable the connector if is in disabled state before uploading the UC plug-in.
Done

2022-06-01 07:21 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +9. The "tags" parameter in filter configuration should match the value of attribute tags configured in filebeat configuration for a connector.
Done

2022-06-15 08:46 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/src/main/java/com/ibm/guardium/mariadb/ParserHelper.java
> +					: ApplicationConstant.CLIENT_IP_STRING);
OK.

2022-06-15 08:54 UTC, Tal-Daniel requested changes

2022-06-15 08:54 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +This is a Logstash filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from the MariaDB audit log into a Guardium record instance (whic
typo: "... MaraidDB queries."

2022-06-15 09:59 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +	- ClientIP - Not avaiable in Audit Logs
Hi Tal,

That field returns hostname as discussed last time as well. and for default values we never mention in the readme. Then why we need to add default value of client ip here?

2022-06-15 10:44 UTC, sandeepkumarverma1 commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +This is a Logstash filter plug-in for the universal connector that is featured in IBM Security Guardium. It parses events and messages from the MariaDB audit log into a Guardium record instance (whic
done

2022-06-15 12:03 UTC, Tal-Daniel commented on filter-plugin/logstash-filter-mariadb-guardium/README.md
> +	- ClientIP - Not avaiable in Audit Logs
My mistake, confused it with clientIP there.

2022-06-15 12:05 UTC, Tal-Daniel approved these changes

2022-06-16 04:43 UTC, PratikshaSonawane approved these changes

2022-06-16 09:32 UTC, merged