AzureSQL UC commit
IBM/universal-connectors pull request #92
Opened 2022-05-12 13:47 UTC by ldmahale108

Signed-off-by: Laxmikant Mahale <Laxmikant.Mahale@ibm.com>

2022-05-12 13:54 UTC, ofer-haim approved these changes
Looks good. Please make sure this is the exact same content the was reviewed and tested in the internal repo

2022-05-12 13:54 UTC, ofer-haim commented on docs/available_plugins.md
> +|            [AzureSQL](../filter-plugin/logstash-filter-azure-sql-guardium/README.md)            | 12.0.2000.8        | Cloud                 | IBM                  | JDBC (pull)
Is there a version of Azure SQL in other Cloud services? If not, I think it's best to write Azure instead of Cloud

2022-05-12 14:11 UTC, ldmahale108 commented on docs/available_plugins.md
> +|            [AzureSQL](../filter-plugin/logstash-filter-azure-sql-guardium/README.md)            | 12.0.2000.8        | Cloud                 | IBM                  | JDBC (pull)
Done.

2022-05-13 12:45 UTC, PratikshaSonawane requested changes

2022-05-13 12:45 UTC, PratikshaSonawane commented on filter-plugin/logstash-filter-azure-sql-guardium/README.md
> +
Please add pagination related information, which helps avert the MemoryIndexOutOfBound exception, as it is added for other JDBC plugins.

2022-05-16 12:16 UTC, ldmahale108 commented on filter-plugin/logstash-filter-azure-sql-guardium/README.md
> +
Done.

2022-05-17 10:58 UTC, PratikshaSonawane approved these changes

2022-05-17 12:09 UTC, merged